const CFG={apiUrl:'https://script.google.com/macros/s/AKfycbx2s0l5A8LAdD1j24395XJSTMd5cEU7QdUkTI8LarDzatF-vVw6ODfm5x7MVJUkP9aB/exec',supportPhone:'7411807675',supportWhatsApp:'917411807675'};
const $=id=>document.getElementById(id);let TOKEN='',HOME=null,DETAIL=null,CART={},CURRENT='home',PAYMENT=null,UPI=null;
const pending=new Map();
window.addEventListener('message',e=>{let p=e.data;try{if(typeof p==='string')p=JSON.parse(p)}catch(_){return}if(!p||!p.requestId||!pending.has(p.requestId))return;const h=pending.get(p.requestId);pending.delete(p.requestId);clearTimeout(h.timer);try{h.frame.remove();h.form.remove()}catch(_){}p.ok?h.resolve(p.result):h.reject(new Error(p.error||'Request failed.'))});
function rpc(method,args=[]){return new Promise((resolve,reject)=>{const id=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()).toString(),frame=document.createElement('iframe'),form=document.createElement('form'),input=document.createElement('input');frame.name=id;frame.style.display=form.style.display='none';form.method='POST';form.action=CFG.apiUrl+'?bridge=1';form.target=id;input.type='hidden';input.name='payload';input.value=JSON.stringify({requestId:id,method,args});form.appendChild(input);document.body.append(frame,form);const timer=setTimeout(()=>{pending.delete(id);try{frame.remove();form.remove()}catch(_){}reject(new Error('Request timed out. Please try again.'))},30000);pending.set(id,{resolve,reject,timer,frame,form});form.submit()})}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'₹ '+Math.round(Number(n||0)).toLocaleString('en-IN');
const digits=s=>String(s||'').replace(/\D/g,'');
const idOf=p=>String(p?.productId||p?.id||p?.jpin||'');
const nameOf=p=>String(p?.productName||p?.name||'Tender Coconut');
const imgOf=p=>String(p?.imageUrl||p?.image||'');
const moqOf=p=>Math.max(1,Number(p?.moq||p?.minOrderQty||p?.minimumOrderQty||1));
const stepOf=p=>Math.max(1,Number(p?.qtyStep||p?.orderStep||p?.step||1));
function toast(s){const t=$('toast');t.textContent=s;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2400)}
function uuid(){return (crypto.randomUUID?crypto.randomUUID():(Date.now()+'-'+Math.random().toString(16).slice(2)))}
function save(){try{localStorage.setItem('nel_b2b_approved_token',TOKEN);if(HOME)localStorage.setItem('nel_b2b_approved_home',JSON.stringify(HOME));localStorage.setItem('nel_b2b_approved_cart',JSON.stringify(Object.fromEntries(Object.entries(CART).map(([k,v])=>[k,v.qty]))))}catch(_){}}
function restoreCart(){try{const q=JSON.parse(localStorage.getItem('nel_b2b_approved_cart')||'{}');CART={};(HOME?.products||[]).forEach(p=>{const id=idOf(p),qty=Number(q[id]||0);if(qty>0)CART[id]={product:p,qty}})}catch(_){CART={}}}
function openApp(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');showView('home');renderAll() }
function showLogin(){ $('app').classList.add('hidden');$('login').classList.remove('hidden');$('ask').classList.add('hidden') }
function showView(v){CURRENT=v;['home','products','cart','orders','schemes','account'].forEach(x=>$(x+'View').classList.toggle('hidden',x!==v));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.v===v));$('askFab').style.display=v==='home'?'grid':'none';if(v==='orders'||v==='schemes')loadDetails();if(v==='products')renderProducts();if(v==='cart')renderCart();window.scrollTo({top:0,left:0,behavior:'auto'})}
function toPerPiece(n,unit){n=Number(n||0);if(!n)return 0;const u=String(unit||'').toLowerCase();if(/quintal|100\s*kg|qtl/.test(u))return n*1.6/100;if(/kg|kilogram/.test(u))return n*1.6;if(/100\s*(piece|pc|nos)|hundred/.test(u))return n/100;return n>250?n*1.6/100:n}
function rateValues(){return (HOME?.marketRates||HOME?.marketPrices||[]).map(r=>toPerPiece(r.modal||r.modalPrice||r.price||r.rate||r.value,r.rateUnit||r.unit||'')).filter(x=>x>0&&x<300)}
function marketText(){const a=rateValues();if(!a.length)return '—';const lo=Math.round(Math.min(...a)),hi=Math.round(Math.max(...a));return lo===hi?money(lo):money(lo)+' - '+Math.round(hi).toLocaleString('en-IN')}
function primaryProduct(){return (HOME?.products||[]).find(p=>/tender|elaneeru/i.test(nameOf(p)))||(HOME?.products||[])[0]||null}
function renderHome(){if(!HOME)return;$('marketPrice').textContent=marketText();const p=primaryProduct();$('vendorPrice').textContent=p?money(p.price):'—';const dt=HOME.marketRatesUpdatedAt;$('marketDate').textContent=dt?String(dt).slice(0,16):'Bengaluru · Estimated per coconut';const ps=(HOME.products||[]).slice(0,2);$('homeProducts').innerHTML=ps.map(homeCard).join('')||'<div class="empty" style="grid-column:1/-1">No live products available.</div>';const b=(HOME.banners||[])[0];if(b){const h=$('heroBanner');const title=b.title||b.offerText;if(title)h.querySelector('h2').innerHTML=esc(title).replace(/\s+-\s+|\s+•\s+/,'<br>');const img=h.querySelector('img');if(b.imageUrl)img.src=b.imageUrl}}
function homeCard(p){const id=esc(idOf(p)),img=imgOf(p),stock=p.stockStatus||'',disabled=/out/i.test(stock);return `<div class="pcard"><div class="pimg">${img?`<img src="${esc(img)}" onerror="this.parentNode.textContent='🥥'">`:'🥥'}</div><div><div class="pname">${esc(nameOf(p))}</div><div class="price">${money(p.price)} / ${esc(p.unit||'piece')}</div><div class="rule">Min. Order: ${moqOf(p)} pcs</div><button class="add" ${disabled?'disabled':''} onclick="add('${id}')">${disabled?'Out of stock':'Add'}</button></div></div>`}
function renderProducts(){if(!HOME)return;const q=String($('productSearch').value||'').toLowerCase(),ps=(HOME.products||[]).filter(p=>!q||nameOf(p).toLowerCase().includes(q));$('productCount').textContent=ps.length+' items';$('productList').innerHTML=ps.map(p=>{const img=imgOf(p),id=esc(idOf(p)),disabled=/out/i.test(p.stockStatus||'');return `<div class="listProduct"><div class="pimg">${img?`<img src="${esc(img)}" onerror="this.parentNode.textContent='🥥'">`:'🥥'}</div><div><div class="pname">${esc(nameOf(p))}</div><div class="price">${money(p.price)} / ${esc(p.unit||'piece')}</div><div class="rule">Min. Order: ${moqOf(p)} pieces${p.availableQty!=null?' · '+esc(p.availableQty)+' available':''}</div></div><button class="add" ${disabled?'disabled':''} onclick="add('${id}')">${disabled?'Out':'Add'}</button></div>`}).join('')||'<div class="empty">No products found.</div>'}
function add(id){const p=(HOME?.products||[]).find(x=>idOf(x)===id);if(!p)return;const min=moqOf(p),step=stepOf(p),current=CART[id]?.qty||0,next=current?current+step:min;if(p.stockTracked&&Number(p.availableQty||0)<next)return toast('Only '+Number(p.availableQty||0)+' available');CART[id]={product:p,qty:next};save();renderCart();updateBadge();toast(nameOf(p)+' added')}
function changeQty(id,dir){const x=CART[id];if(!x)return;const min=moqOf(x.product),step=stepOf(x.product),n=x.qty+dir*step;if(n<min)delete CART[id];else if(x.product.stockTracked&&n>Number(x.product.availableQty||0))return toast('Stock limit reached');else x.qty=n;save();renderCart();updateBadge()}
function renderCart(){const xs=Object.values(CART),total=xs.reduce((s,x)=>s+x.qty*Number(x.product.price||0),0),qty=xs.reduce((s,x)=>s+x.qty,0);$('cartItems').innerHTML=xs.map(x=>{const p=x.product,id=esc(idOf(p)),img=imgOf(p);return `<div class="cartRow"><div class="pimg">${img?`<img src="${esc(img)}" onerror="this.parentNode.textContent='🥥'">`:'🥥'}</div><div><div class="pname">${esc(nameOf(p))}</div><div class="price">${money(p.price)} / ${esc(p.unit||'piece')}</div><div class="cartCtl"><button onclick="changeQty('${id}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${id}',1)">+</button></div></div><div><b>${money(x.qty*Number(p.price||0))}</b><br><button class="remove" onclick="removeItem('${id}')">×</button></div></div>`}).join('')||'<div class="empty">Your cart is empty.</div>';$('cartSummary').innerHTML=`<div class="sum"><span>Total Items</span><b>${qty}</b></div><div class="sum"><span>Total Amount</span><b>${money(total)}</b></div>`;$('checkoutBtn').disabled=!xs.length;updateBadge()}
function removeItem(id){delete CART[id];save();renderCart()}
function updateBadge(){const n=Object.keys(CART).length;$('cartBadge').textContent=n;$('cartBadge').classList.toggle('hidden',!n)}
async function loadDetails(force=false){if(!TOKEN)return;if(DETAIL&&!force){renderDetails();return}try{DETAIL=await rpc('getB2BAppDataV9',[TOKEN]);renderDetails()}catch(e){if(/token|login|session/i.test(e.message))logout(false);else toast(e.message)}}
function renderDetails(){renderOrders();renderSchemes();renderAccount()}
function orderStatusClass(s){s=String(s||'').toLowerCase();return /deliver/.test(s)?'delivered':/transit|dispatch|route/.test(s)?'transit':'received'}
function renderOrders(){const os=DETAIL?.orders||[];$('ordersList').innerHTML=os.map(o=>`<div class="orderCard"><div><b>${esc(o.orderId||o['Order ID']||'Order')}</b><small>${esc(o.orderedAt||o.date||o.createdAt||'')} · ${esc(o.totalQty||o.quantity||'')} ${o.totalQty||o.quantity?'pieces':''}</small><b>${money(o.totalAmount||o.amount||0)}</b></div><span class="status ${orderStatusClass(o.status)}">${esc(o.status||'Order Received')}</span></div>`).join('')||'<div class="empty">No orders yet.</div>'}
function renderSchemes(){const t=DETAIL?.target||null;let target='';if(t){const pct=Math.max(0,Math.min(100,Number(t.progressPct||t.progress||0)));target=`<div class="schemeBox"><h4>🎯 My Target</h4><p>${esc(t.label||t.period||'Current target')}</p><div class="progress"><i style="width:${pct}%"></i></div><div class="tier"><span>Achieved</span><span>${esc(t.achieved||t.current||0)}</span></div><div class="tier"><span>Target</span><span>${esc(t.target||t.goal||0)}</span></div></div>`}$('schemeContent').innerHTML=`<div class="schemeBox"><h4>🎁 Volume Discount Scheme</h4><p>Order more. Save more.</p><div class="tier"><span>50 - 99 pieces</span><span>Base Price</span></div><div class="tier"><span>100 - 299 pieces</span><span>₹ 1 off / piece</span></div><div class="tier"><span>300+ pieces</span><span>₹ 2 off / piece</span></div></div>${target}<div class="schemeBox"><h4>🎯 Monthly Target Scheme</h4><p>Reach your monthly target and get additional benefits.</p></div>`}
function initials(n){return String(n||'NE').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function renderAccount(){const v=HOME?.vendor||{};$('accountHead').innerHTML=`<div class="avatar">${esc(initials(v.ownerName||v.businessName))}</div><div><b>${esc(v.ownerName||v.businessName||'Business Partner')}</b><small>+91 ${esc(v.mobile||'')}</small><small>${esc(v.businessName||'Active Partner')}</small></div>`}
function renderAll(){renderHome();renderProducts();renderCart();renderDetails();updateBadge()}
function payload(){return{items:Object.values(CART).map(x=>({productId:idOf(x.product),quantity:x.qty})),deliverySlot:'Standard',deliveryAddress:HOME?.vendor?.address||'',area:HOME?.vendor?.area||'',deliveryCharge:0}}
async function openCheckout(){if(!Object.keys(CART).length)return toast('Cart is empty');$('checkoutSheet').classList.remove('hidden');try{PAYMENT=await rpc('getB2BPaymentConfigV916',[TOKEN]);$('upiBtn').style.display=PAYMENT?.methods?.includes('UPI')?'block':'none'}catch(_){$('upiBtn').style.display='none'}}
async function placeCod(){const b=$('codBtn');b.disabled=true;try{const p=Object.assign({},payload(),{paymentType:'COD',clientRequestId:uuid()}),r=await rpc('placeB2BOrderV9',[TOKEN,p]);CART={};save();$('checkoutSheet').classList.add('hidden');toast('Order placed · '+r.orderId);await loadDetails(true);showView('orders')}catch(e){toast(e.message)}finally{b.disabled=false}}
async function prepareUpi(){const b=$('upiBtn');b.disabled=true;try{UPI=await rpc('prepareB2BUpiPaymentV916',[TOKEN,payload()]);$('checkoutSheet').classList.add('hidden');$('upiInfo').innerHTML=`Amount: <b>${money(UPI.amount)}</b><br>Pay to: <b>${esc(UPI.upiId)}</b>`;$('openUpi').href=UPI.upiUri||'#';$('utr').value='';$('upiSheet').classList.remove('hidden')}catch(e){toast(e.message)}finally{b.disabled=false}}
async function submitUpi(){const utr=$('utr').value.trim();if(!utr)return toast('Enter UTR / transaction number');const b=$('submitUpi');b.disabled=true;try{const r=await rpc('submitB2BUpiOrderV916',[TOKEN,UPI.paymentId,utr,payload()]);CART={};save();$('upiSheet').classList.add('hidden');toast('Order received · '+r.orderId);await loadDetails(true);showView('orders')}catch(e){toast(e.message)}finally{b.disabled=false}}
function openAsk(){resetAsk();$('ask').classList.remove('hidden')}
function closeAsk(){$('ask').classList.add('hidden')}
function resetAsk(){$('quickBlock').classList.remove('hidden');$('chatDynamic').innerHTML='';$('askInput').value=''}
function userBubble(q){return `<div class="bubble userBubble">${esc(q)}</div>`}
function botBubble(h){return `<div class="bubble botBubble">${h}</div><div class="askTime">${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div>`}
function routeAskType(type,question){if(type!=='free')return type;const q=String(question||'').toLowerCase();if(/price|rate/.test(q))return'price';if(/order|track|delivery/.test(q))return'orders';if(/stock|available/.test(q))return'stock';if(/scheme|target/.test(q))return'schemes';if(/pay|upi|cod/.test(q))return'payment';if(/support|help|call|whatsapp/.test(q))return'support';return'unknown'}
async function answerAsk(type,question){type=routeAskType(type,question);$('quickBlock').classList.add('hidden');const d=$('chatDynamic');d.insertAdjacentHTML('beforeend',userBubble(question));let html='';if(type==='price'){const p=primaryProduct();html=`Today’s market price for tender coconut is <b>${esc(marketText())} per piece.</b><br><br><b>Your price is ${p?money(p.price):'not available'} per piece</b>${p?`<br>(Minimum order: ${moqOf(p)} pieces).`:''}`}else if(type==='stock'){const ps=HOME?.products||[];html=ps.length?ps.slice(0,5).map(p=>`<b>${esc(nameOf(p))}</b> — ${/out/i.test(p.stockStatus||'')?'Out of stock':p.availableQty!=null?esc(p.availableQty)+' available':'Available'}`).join('<br>'):'No live stock data is available.'}else if(type==='orders'){await loadDetails();const os=(DETAIL?.orders||[]).slice(0,3);html=os.length?'Here are your recent orders:'+os.map(o=>`<div class="chatOrder"><div><b>${esc(o.orderId||'Order')}</b><small>${esc(o.orderedAt||o.date||'')}</small><b>${money(o.totalAmount||o.amount||0)}</b></div><span class="status ${orderStatusClass(o.status)}">${esc(o.status||'Received')}</span></div>`).join(''):'You do not have any recent orders.'}else if(type==='schemes'){await loadDetails();html='Your active launch schemes are available in the <b>Schemes</b> tab. I can also show your target progress there.'}else if(type==='payment'){try{const p=await rpc('getB2BPaymentConfigV916',[TOKEN]);html='Available payment methods: <b>'+esc((p.methods||['COD']).join(', '))+'</b>.<br>Choose your payment method during checkout.'}catch(_){html='Cash on Delivery is available. UPI is shown during checkout when enabled.'}}else if(type==='support'){html=`Customer support: <b>${CFG.supportPhone}</b><br>You can call or WhatsApp Native Elaneeru support.`}else{html='I can help with <b>prices, orders, stock, schemes, payments and support</b>. Please ask about one of these.'}d.insertAdjacentHTML('beforeend',botBubble(html));$('chat').scrollTop=$('chat').scrollHeight}
function qLabel(t){return({price:'What is today’s price?',orders:'Show my recent orders',stock:'Check stock availability',schemes:'What schemes are available?',payment:'How do I make payment?',support:'Talk to customer support'})[t]||t}
async function loginNow(){const m=digits($('mobile').value),p=$('pin').value.trim(),b=$('loginBtn');if(m.length<10)return toast('Enter a valid mobile number');if(!p)return toast('Enter your PIN');b.disabled=true;b.textContent='Checking…';try{const r=await rpc('vendorLogin',[m,p]);TOKEN=r.token;HOME=r.home||await rpc('getB2BHomeFastV1000',[TOKEN]);DETAIL=null;restoreCart();save();$('pinSheet').classList.add('hidden');openApp()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Login'}}
function logout(msg=true){TOKEN='';HOME=null;DETAIL=null;CART={};try{localStorage.removeItem('nel_b2b_approved_token');localStorage.removeItem('nel_b2b_approved_home');localStorage.removeItem('nel_b2b_approved_cart')}catch(_){}showLogin();if(msg)toast('Logged out')}
async function restore(){try{TOKEN=localStorage.getItem('nel_b2b_approved_token')||'';HOME=JSON.parse(localStorage.getItem('nel_b2b_approved_home')||'null')}catch(_){}if(!TOKEN||!HOME)return;restoreCart();openApp();try{HOME=await rpc('getB2BHomeFastV1000',[TOKEN]);save();restoreCart();renderAll()}catch(e){if(/token|login|session/i.test(e.message))logout(false)}}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)showView(go.dataset.go);const nav=e.target.closest('.nav button');if(nav)showView(nav.dataset.v);const q=e.target.closest('.quickQ');if(q)answerAsk(q.dataset.q,qLabel(q.dataset.q))});
$('continueBtn').onclick=()=>{const m=digits($('mobile').value);if(m.length<10)return toast('Enter a valid mobile number');$('pinSheet').classList.remove('hidden');setTimeout(()=>$('pin').focus(),80)};$('cancelPin').onclick=()=>$('pinSheet').classList.add('hidden');$('loginBtn').onclick=loginNow;$('pin').addEventListener('keydown',e=>{if(e.key==='Enter')loginNow()});
$('backBtn').onclick=()=>showView('home');$('productSearch').oninput=renderProducts;$('clearCartBtn').onclick=()=>{CART={};save();renderCart()};$('checkoutBtn').onclick=openCheckout;$('closeCheckout').onclick=()=>$('checkoutSheet').classList.add('hidden');$('codBtn').onclick=placeCod;$('upiBtn').onclick=prepareUpi;$('cancelUpi').onclick=()=>$('upiSheet').classList.add('hidden');$('submitUpi').onclick=submitUpi;$('refreshOrdersBtn').onclick=()=>loadDetails(true);$('logoutBtn').onclick=()=>logout();$('supportBtn').onclick=()=>window.open('https://wa.me/'+CFG.supportWhatsApp,'_blank');$('askFab').onclick=openAsk;$('closeAsk').onclick=closeAsk;$('sendAsk').onclick=()=>{const q=$('askInput').value.trim();if(q){$('askInput').value='';answerAsk('free',q)}};$('askInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('sendAsk').click()});
renderCart();restore();