'use strict';
const CFG={apiUrl:'https://script.google.com/macros/s/AKfycbx2s0l5A8LAdD1j24395XJSTMd5cEU7QdUkTI8LarDzatF-vVw6ODfm5x7MVJUkP9aB/exec',build:'1600'};
const $=id=>document.getElementById(id),pending=new Map();
let TOKEN='',DATA=null,cart={},selectedQty={},category='All',orderFilter='All',CURRENT='login',activeOrderId='',loading=null,confirming=false,voice=null,bi=0,installPrompt=null,sessionEpoch=0,refreshSerial=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const safeUrl=v=>/^https?:\/\//i.test(String(v||''))?String(v):'';
const uid=()=>crypto.randomUUID();
function priceHtml(p){const sell=Number(p.price)||0,base=Number(p.basePrice)||0;return (base>sell&&sell>0?'<s class="basePrice" style="color:var(--mut);font-size:9px">'+money(base)+'</s> ':'')+'<b>'+money(sell)+'</b> / '+esc(p.unit||'piece')}
function msg(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(msg.timer);msg.timer=setTimeout(()=>$('toast').classList.remove('show'),4500)}
// HtmlService may nest its bridge inside a Google sandbox frame. Match an
// unpredictable per-request nonce AND trusted Google origin, not frame depth.
window.addEventListener('message',e=>{
  if(!/^https:\/\/(?:script\.google\.com|(?:[a-z0-9-]+\.)?script\.googleusercontent\.com|[a-z0-9-]+-script\.googleusercontent\.com)$/i.test(e.origin))return;
  let d=e.data;try{if(typeof d==='string')d=JSON.parse(d)}catch(_){return}
  if(d?.nelBridge!==true)return;const p=d.payload,h=pending.get(p?.requestId);if(!h)return;
  pending.delete(p.requestId);h.cleanup();p.ok?h.resolve(p.result):h.reject(new Error(p.error||'Request failed.'));
});
function rpc(method,args=[]){return new Promise((resolve,reject)=>{
  const id=uid(),frame=document.createElement('iframe'),form=document.createElement('form'),input=document.createElement('input');
  frame.name='nel_'+id;frame.hidden=true;frame.title='Secure app request';form.method='POST';form.action=CFG.apiUrl+'?bridge=1';form.target=frame.name;form.hidden=true;
  input.type='hidden';input.name='payload';input.value=JSON.stringify({method,args,requestId:id});form.append(input);document.body.append(frame,form);
  const timer=setTimeout(()=>{pending.delete(id);cleanup();reject(new Error('Request timed out. Retry using the same cart; duplicate orders are prevented.'))},method==='getB2BWorkspaceV5'?15000:45000);
  function cleanup(){clearTimeout(timer);setTimeout(()=>{frame.remove();form.remove()},50)}pending.set(id,{resolve,reject,cleanup});form.submit();
})}
const products=()=>DATA?.products||[],orders=()=>DATA?.orders||[],vendor=()=>DATA?.vendor||{};
function product(id){return products().find(p=>p.productId===id)}
function stockOf(p){return p.stockTracked?Math.max(0,Number(p.availableQty||0)):Infinity}
function minQty(p){const step=Math.max(1,Number(p.qtyStep)||1);return Math.ceil(Math.max(1,Number(p.moq)||1)/step)*step}
function totals(){return Object.entries(cart).reduce((t,[id,n])=>{const p=product(id);if(p){t.qty+=n;t.amount+=n*Number(p.price||0)}return t},{qty:0,amount:0})}
function cartValid(){return Object.keys(cart).length>0&&Object.entries(cart).every(([id,n])=>{const p=product(id);return p&&Number.isInteger(n)&&n>=minQty(p)&&n%Math.max(1,Number(p.qtyStep)||1)===0&&n<=stockOf(p)})}
function orderQty(o){return (o.items||[]).reduce((n,i)=>n+Number(i.quantity||0),0)}
function storageGet(key,where=localStorage){try{return where.getItem(key)}catch(_){return null}}
function storageSet(key,value){try{localStorage.setItem(key,value)}catch(_){}}
function parse(raw){try{return JSON.parse(raw)}catch(_){return null}}
function cartKey(){return 'nel_b2b_v5_cart:'+vendor().vendorId}
function saveCart(){if(!DATA)return;storageSet(cartKey(),JSON.stringify(cart));clearRequest()}
function clearRequest(){try{localStorage.removeItem('nel_b2b_v5_order_request')}catch(_){}}
async function persistSession(){storageSet('nel_b2b_token',TOKEN);storageSet('nel_b2b_token_saved_at',String(Date.now()));storageSet('nel_b2b_green_session',JSON.stringify({token:TOKEN,savedAt:Date.now()}));void window.NEL_B2B_DB?.set('sessionToken',{token:TOKEN,savedAt:Date.now()})?.catch(()=>{})}
function isSessionError(e){return /session.*(expired|invalid)|invalid token|vendor is inactive|please (login|sign in)/i.test(e.message)}
async function refresh(silent=false){
  if(!TOKEN)return false;if(loading)return loading;const token=TOKEN,epoch=sessionEpoch,serial=++refreshSerial;
  loading=(async()=>{try{const data=await rpc('getB2BWorkspaceV5',[token]);if(TOKEN!==token||sessionEpoch!==epoch)return false;
    const first=!DATA;DATA=data;if(first){cart=parse(storageGet(cartKey()))||{};if(!cart||Array.isArray(cart)||typeof cart!=='object')cart={};}
    render();if(CURRENT==='place'&&!confirming)refreshCheckoutView();sessionRestoreUi(false);if(CURRENT==='login')show('home');return true;
  }catch(e){if(TOKEN!==token||sessionEpoch!==epoch)return false;if(isSessionError(e)){logout(false);msg(e.message)}else{if(!silent)msg(e.message);if(!DATA)showRecovery()}return false;}finally{if(serial===refreshSerial)loading=null}})();return loading;
}
function sessionRestoreUi(active){
 const panel=$('login').querySelector('.loginPanel');panel.classList.toggle('restoring',active);
 if(!active){$('restoreNotice')?.remove();$('recoverSession')?.remove();return}
 if(!$('restoreNotice'))panel.insertAdjacentHTML('beforeend','<div id="restoreNotice" class="retryNote" role="status">Restoring your account…</div>');
}
function showRecovery(){sessionRestoreUi(true);$('restoreNotice')?.remove();$('recoverSession')?.remove();$('login').querySelector('.loginPanel').insertAdjacentHTML('beforeend','<div id="recoverSession" class="retryNote">Your session was found, but account data could not load.<button class="wide" onclick="retrySession()">Retry loading account</button><button class="wide" onclick="logout()">Sign out</button></div>')}
async function retrySession(){$('recoverSession')?.remove();sessionRestoreUi(true);if(await refresh())show('home')}
function show(id){if(id!=='login'&&(!TOKEN||!DATA)){msg('Sign in to access your business account');id='login'}const s=$(id);if(!s?.classList.contains('screen'))return msg('This page is unavailable');CURRENT=id;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('hidden',x!==s));s.scrollTop=0;const content=s.querySelector(':scope > .pad');if(content)content.scrollTop=0;if(voice&&id!=='support'){try{voice.abort()}catch(_){}voice=null}updateNavigation(id);
  if(id==='products')renderProducts();if(id==='cart')renderCart();if(id==='orders')renderOrders();if(id==='payments'||id==='credit')renderPayments();if(['account','profile','shop','address'].includes(id))renderProfile(true);if(id==='schemes')schemeTab(false);
}
function goPin(){const m=$('loginPhone').value.trim();if(!/^[6-9]\d{9}$/.test(m))return msg('Enter your registered 10-digit mobile number');$('phoneEcho').textContent='+91 '+m;$('phoneStep').classList.add('hidden');$('pinStep').classList.remove('hidden');$('loginPin').focus()}
function backPhone(){$('pinStep').classList.add('hidden');$('phoneStep').classList.remove('hidden');$('loginPin').value=''}
async function doLogin(){const m=$('loginPhone').value.trim(),pin=$('loginPin').value;if(!/^[6-9]\d{9}$/.test(m)||!/^\d{4}$/.test(pin))return msg('Enter your mobile number and 4-digit PIN');const btn=document.querySelector('#pinStep .wide');if(btn.disabled)return;btn.disabled=true;btn.textContent='Signing in…';const epoch=++sessionEpoch;
  try{const r=await rpc('vendorLogin',[m,pin]);if(epoch!==sessionEpoch)return;if(!r.token)throw new Error('Unable to sign in');TOKEN=r.token;DATA=null;cart={};selectedQty={};await persistSession();$('loginPin').value='';if(await refresh())show('home');}
  catch(e){msg(e.message)}finally{btn.disabled=false;btn.textContent='Login'}
}
function logout(notify=true){if(voice){try{voice.abort()}catch(_){}voice=null}const old=TOKEN;sessionEpoch++;refreshSerial++;loading=null;TOKEN='';DATA=null;cart={};selectedQty={};activeOrderId='';clearRequest();
  ['nel_b2b_token','nel_b2b_token_saved_at','nel_b2b_green_session','nel_b2b_approved_token','nel_b2b_approved_home','nel_b2b_data_cache'].forEach(k=>{for(const s of [localStorage,sessionStorage])try{s.removeItem(k)}catch(_){}});
  window.NEL_B2B_DB?.set('sessionToken',null)?.catch(()=>{});window.NEL_B2B_DB?.set('businessData',null)?.catch(()=>{});window.NEL_B2B_DB?.set('profile',null)?.catch(()=>{});$('loginPin').value='';sessionRestoreUi(false);backPhone();show('login');if(old&&notify)rpc('vendorLogout',[old]).catch(()=>{});
}
function registerVendor(){extraScreen('registration','Business Partner Registration','<div class="card"><b>Register with Native Elaneeru</b><p class="sub">Our vendor onboarding team will register your business, confirm service availability and issue your login PIN.</p><a class="wide" style="display:block;text-align:center;text-decoration:none" href="tel:+917411807675">Call Vendor Support</a><a class="wide" style="display:block;text-align:center;text-decoration:none" href="https://wa.me/917411807675?text=I%20would%20like%20to%20register%20as%20a%20Native%20Elaneeru%20business%20partner" target="_blank" rel="noopener">Contact on WhatsApp</a></div>','login');const s=$('registration');CURRENT='registration';document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('hidden',x!==s))}
function render(){renderBanners();renderMarket();renderProducts();renderCart();renderOrders();renderProfile();renderDelivery();renderPayments();renderTickets();renderNotifications();if(CURRENT==='schemes')schemeTab(false)}
function renderBanners(){const list=DATA?.banners?.length?DATA.banners:[{title:'Fresh supply for your business',subtitle:'Your prices, supply orders and benefits in one place.',redirectType:'PRODUCTS'}];$('bannerTrack').innerHTML=list.map((b,i)=>`<div class="hero ${['a','b','c'][i%3]}"><h1>${esc(b.title||'Native Elaneeru')}</h1><p>${esc(b.offerText||b.subtitle||'')}</p><button class="cta" data-banner="${i}">View details</button>${safeUrl(b.imageUrl)?`<img src="${esc(safeUrl(b.imageUrl))}" alt="" decoding="async">`:'<img src="../b2c/images/tender-coconut-v2.webp" alt="Tender coconut" decoding="async">'}</div>`).join('');$('bannerDots').innerHTML=list.map((_,i)=>`<i role="button" tabindex="0" aria-label="Banner ${i+1}" data-dot="${i}"></i>`).join('');setBanner(bi)}
function setBanner(i){const count=$('bannerTrack').children.length;if(!count)return;bi=(i+count)%count;$('bannerTrack').style.transform='translateX(-'+bi*100+'%)';Array.from($('bannerDots').children).forEach((d,j)=>d.classList.toggle('on',j===bi))}
function bannerAction(i){const b=DATA?.banners?.[i]||{},type=String(b.redirectType||'').toUpperCase();if(type.includes('URL')&&safeUrl(b.redirectValue))return window.open(safeUrl(b.redirectValue),'_blank','noopener');show(type.includes('SCHEME')||type.includes('TARGET')?'schemes':'products')}
function renderMarket(){const rates=(DATA?.marketRates||DATA?.marketPrices||[]).filter(r=>Number(r.modalRate||r.marketPrice||r.modal||r.price)>0).slice(0,3);const p=products()[0];$('marketCard').innerHTML='<div class="row"><b style="font-size:11px">Market Price Reference</b><span class="pill">REFERENCE</span></div>'+rates.map(r=>`<div class="row" style="margin-top:10px"><div><b style="font-size:11px">${esc(r.market||r.area||'Market')}</b><div class="sub">${esc(r.rateDate||r.updatedAt||'')} · ${esc(r.rateUnit||r.unit||'Unit not specified')}</div></div><b>${money(r.modalRate||r.marketPrice||r.modal||r.price)}</b></div>`).join('')+(rates.length?'':'<p class="sub">No market reference has been published.</p>')+(p?`<div class="meta" style="grid-template-columns:1fr"><div><small>Your NE price · ${esc(p.productName)}</small><b style="font-size:16px">${priceHtml(p)}</b></div></div>`:'')}
function renderProducts(){const search=($('productSearch')?.value||'').trim().toLowerCase();$('plist').innerHTML=products().filter(p=>(category==='All'||p.productName.toLowerCase().includes(category.toLowerCase()))&&p.productName.toLowerCase().includes(search)).map(p=>{const id=encodeURIComponent(p.productId),n=selectedQty[p.productId]||cart[p.productId]||minQty(p),max=stockOf(p),off=max<minQty(p);return `<div class="product"><img src="${esc(safeUrl(p.imageUrl)||'../b2c/images/tender-coconut-v2.webp')}" alt="${esc(p.productName)}" loading="lazy"><div><div class="pname">${esc(p.productName)}</div><div class="price">${priceHtml(p)}</div><div class="moq">MOQ: ${Number(p.moq)||1} · Step: ${Number(p.qtyStep)||1}</div><div class="moq" style="color:${off?'var(--red)':'var(--g)'}">${off?'Out of stock':Number.isFinite(max)?max+' available':'Supply confirmed when order is accepted'}</div><div class="qty"><button aria-label="Decrease ${esc(p.productName)}" data-qty="${id}" data-dir="-1" ${off||n<=minQty(p)?'disabled':''}>−</button><b>${n}</b><button aria-label="Increase ${esc(p.productName)}" data-qty="${id}" data-dir="1" ${off||n+Math.max(1,Number(p.qtyStep)||1)>max?'disabled':''}>+</button></div></div><button class="add" data-add="${id}" ${off?'disabled':''}>${off?'Unavailable':cart[p.productId]?'Update':'Add'}</button></div>`}).join('')||'<div class="card sub">No products match your search.</div>';
  const summary=$('products').querySelector('.mainSummary');if(summary){const b=summary.querySelectorAll('b');b[0].textContent=products().filter(p=>stockOf(p)>=minQty(p)).length+' Products';b[1].textContent=products().length?Math.min(...products().map(p=>Number(p.moq)||1))+' units':'—';b[2].textContent='Live catalogue'}
}
function filterProducts(c,b){category=c;document.querySelectorAll('#products .chip').forEach(x=>x.classList.toggle('on',x===b));renderProducts()}
function q(id,d,inCart=false){const p=product(id);if(!p)return;const n=Math.max(minQty(p),(inCart?cart[id]:selectedQty[id]||cart[id]||minQty(p))+d*Math.max(1,Number(p.qtyStep)||1));if(n>stockOf(p))return msg('Only '+stockOf(p)+' available');selectedQty[id]=n;if(inCart){cart[id]=n;saveCart();renderCart()}renderProducts()}
function add(id){const p=product(id);if(!p)return;const n=selectedQty[id]||cart[id]||minQty(p);if(n>stockOf(p))return msg('Stock changed. Refresh and review quantities.');cart[id]=n;saveCart();renderCart();renderProducts();msg('Cart updated')}
function removeItem(id){delete cart[id];delete selectedQty[id];saveCart();renderCart();renderProducts()}
function renderCart(){const t=totals();$('cartList').innerHTML=Object.entries(cart).map(([id,n])=>{const p=product(id),key=encodeURIComponent(id);if(!p)return `<div class="cartRow"><div class="sub">This product is no longer available.</div><button class="chip" data-remove="${key}">Remove</button></div>`;return `<div class="cartRow"><img src="${esc(safeUrl(p.imageUrl)||'../b2c/images/tender-coconut-v2.webp')}" alt="${esc(p.productName)}"><div><div class="pname">${esc(p.productName)}</div><div class="price">${priceHtml(p)}</div>${n>stockOf(p)?'<div class="sub" style="color:var(--red)">Quantity exceeds current stock</div>':''}<div class="qty"><button data-cart-qty="${key}" data-dir="-1" ${n<=minQty(p)?'disabled':''}>−</button><b>${n}</b><button data-cart-qty="${key}" data-dir="1" ${n+Math.max(1,Number(p.qtyStep)||1)>stockOf(p)?'disabled':''}>+</button></div><button class="chip" data-remove="${key}">Remove</button></div><b>${money(n*p.price)}</b></div>`}).join('')||'<div class="emptyState"><div class="ico">🛒</div><b>Your cart is empty</b><p>Add at least the minimum order quantity from Products.</p><button class="wide" onclick="show(\'products\')">Browse Products</button></div><div class="infoPanel"><b>MOQ Reminder</b><p>MOQ is the minimum starting quantity. Increase quantities using the product’s step.</p></div>';$('tq').textContent=t.qty+' units';$('ta').textContent=money(t.amount);$('checkoutBtn').disabled=!cartValid();$('cartSummary').classList.toggle('hidden',!t.qty)}
let pricingBusy=false;
const POLL_MS=5000;
async function pollPricing(){
  if(!TOKEN||!DATA||pricingBusy||confirming||loading||document.visibilityState!=='visible'||CURRENT==='upi')return;
  pricingBusy=true;const token=TOKEN,epoch=sessionEpoch;
  try{const result=await rpc('getB2BLivePricingV950',[token]);if(TOKEN!==token||epoch!==sessionEpoch||!result?.ok||!Array.isArray(result.products))return;
    let changed=false,up=false,down=false;const before=new Map(products().map(p=>[p.productId,p]));
    const next=result.products.map(fresh=>{const old=before.get(fresh.productId)||{};const oldPrice=Number(old.price),newPrice=Number(fresh.price);if(oldPrice!==newPrice||Number(old.basePrice)!==Number(fresh.basePrice)||old.moq!==fresh.moq||old.qtyStep!==fresh.qtyStep)changed=true;if(old.price!==undefined){up=up||newPrice>oldPrice;down=down||newPrice<oldPrice;}return {...old,...fresh}});
    if(next.length!==products().length)changed=true;if(!changed)return;
    DATA.products=next;renderProducts();renderCart();renderMarket();
    // Keep the chosen schedule and payment method when totals change.
    if(CURRENT==='place')refreshCheckoutView();
    storageSet('nel_b2b_last_prices_v5_'+vendor().vendorId,JSON.stringify(next.map(p=>({productId:p.productId,price:p.price}))));
    msg(up&&down?'Your prices changed. Review your cart.':up?'Prices increased due to market uptrend. Review your cart.':down?'We have a better price for you. Your cart is updated.':'Product pricing details updated.');
  }catch(e){if(TOKEN===token&&epoch===sessionEpoch&&isSessionError(e)){logout(false);msg(e.message)}}finally{pricingBusy=false}
}
setInterval(pollPricing,POLL_MS);
function renderDelivery(){const o=orders().find(o=>!['DELIVERED','CANCELLED','REJECTED'].includes(String(o.status).toUpperCase())),card=$('home').querySelector('.delivery');card.classList.toggle('hidden',!o);if(!o)return;activeOrderId=o.orderId;card.querySelector('.sub').textContent='Order #'+o.orderId;card.querySelector('.pill').textContent=o.status;const b=card.querySelectorAll('.meta b');b[0].textContent=o.deliveryDate||'Pending';b[1].textContent=orderQty(o)+' units';b[2].textContent='View tracking'}
function renderOrders(){const list=orders().filter(o=>orderFilter==='All'||orderFilter==='Processing'&&!['DELIVERED','CANCELLED','REJECTED','OUT FOR DELIVERY'].includes(o.status.toUpperCase())||orderFilter==='In Transit'&&o.status.toUpperCase()==='OUT FOR DELIVERY'||orderFilter.toUpperCase()===o.status.toUpperCase());$('orderList').innerHTML=list.map(o=>`<div class="orderCard"><div class="row"><div><b>#${esc(o.orderId)}</b><div class="sub">${esc(o.orderedAt)} • ${orderQty(o)} units</div></div><span class="pill">${esc(o.status)}</span></div><div class="row" style="margin-top:9px"><div class="amt">${money(o.amount)}</div><button class="cta" data-track="${encodeURIComponent(o.orderId)}">View details ›</button></div><p class="sub">${esc(o.paymentType)} · ${esc(o.paymentStatus||'Payment pending')}</p><div class="row"><button class="chip" data-invoice="${encodeURIComponent(o.orderId)}">Invoice</button><button class="chip" data-reorder="${encodeURIComponent(o.orderId)}">Reorder</button></div></div>`).join('')||'<div class="emptyState"><div class="ico">📋</div><b>No orders in this category</b><p>Your supply orders will appear here.</p></div>';const b=$('orders').querySelector('.mainSummary')?.querySelectorAll('b');if(b){b[0].textContent=orders().filter(o=>!['Delivered','Cancelled','Rejected'].includes(o.status)).length+' Orders';b[1].textContent=orders().filter(o=>o.status==='Delivered').length+' Orders';b[2].textContent=orders().reduce((n,o)=>n+orderQty(o),0)+' units'}}
function filterOrders(f,b){orderFilter=f;document.querySelectorAll('#orders .orderTabs .chip').forEach(x=>x.classList.toggle('on',x===b));renderOrders()}
function reorder(id){const o=orders().find(x=>x.orderId===id);if(!o)return;cart={};selectedQty={};let adjusted=false;for(const i of o.items||[]){const p=product(i.productId);if(!p){adjusted=true;continue}const step=Math.max(1,Number(p.qtyStep)||1),max=stockOf(p),n=Math.min(Math.ceil(Math.max(i.quantity,minQty(p))/step)*step,Number.isFinite(max)?Math.floor(max/step)*step:Infinity);if(n<minQty(p)){adjusted=true;continue}cart[p.productId]=n;if(n!==i.quantity)adjusted=true;}saveCart();show('cart');msg(adjusted?'Reorder adjusted to current products and stock. Review quantities and prices.':'Reorder uses your current prices. Review before confirming.')}
function beginCheckout(){if(confirming)return msg('Your order is still being submitted. Please wait.');if(!cartValid())return msg('Review products, quantities and stock before checkout');renderCheckout();show('place')}
function refreshCheckoutView(){
 const choice=$('deliveryChoice'),previous=choice?.value===''?null:choice?._slots?.[Number(choice.value)],pay=document.querySelector('input[name="pay"]:checked')?.value||'COD';
 renderCheckout();
 if(previous){const idx=$('deliveryChoice')._slots.findIndex(s=>s.date===previous.date&&s.slot===previous.slot);if(idx>=0)$('deliveryChoice').value=String(idx)}
 const radio=document.querySelector('input[name="pay"][value="'+pay+'"]');if(radio&&!radio.disabled)radio.checked=true;
}
function renderCheckout(){const t=totals(),cards=$('place').querySelectorAll('.card');cards[0].innerHTML='<b>Delivery Address</b><p class="sub">'+esc(vendor().businessName)+' • '+esc(vendor().address||'Contact support to add your delivery address')+'</p>';const slots=(DATA.deliverySlots||[]).filter(s=>s.availableQty>=t.qty);cards[1].innerHTML='<b>Delivery Date & Slot</b><div class="field" style="margin-top:10px"><label for="deliveryChoice">Preferred schedule</label><select id="deliveryChoice"><option value="">Earliest available — confirm with operations</option>'+slots.map((s,i)=>'<option value="'+i+'">'+esc(s.date+' · '+s.slot)+'</option>').join('')+'</select></div><p class="sub">'+(slots.length?'Published slots are checked again when the order is accepted.':'No delivery slots are published for your area yet. Your order will await scheduling by operations.')+'</p>';$('deliveryChoice')._slots=slots;
  const methods=DATA.paymentConfig?.methods||['COD'];cards[2].innerHTML='<b>Payment Method</b>'+['COD','UPI','CREDIT'].map(m=>'<p style="font-size:11px"><label><input type="radio" name="pay" value="'+m+'" '+(m==='COD'?'checked ':'')+(!methods.includes(m)||m==='CREDIT'&&Number(vendor().availableCredit)<t.amount?'disabled ':'')+'>'+({COD:' Cash on Delivery (COD)',UPI:' UPI — submit UTR for verification',CREDIT:' Credit — '+money(vendor().availableCredit)+' available'}[m])+'</label></p>').join('');$('checkoutSummary').innerHTML='<b>Order Summary</b><div class="summary" style="margin-top:8px">'+Object.entries(cart).map(([id,n])=>'<div><span>'+esc(product(id).productName)+'<br><span class="sub">'+n+' × '+money(product(id).price)+'</span></span><b>'+money(n*product(id).price)+'</b></div>').join('')+'<div><span>Total quantity</span><b>'+t.qty+' units</b></div><div><span>Subtotal</span><b>'+money(t.amount)+'</b></div><div><span>Delivery charge</span><b>₹0</b></div><div><span>Discount</span><b>₹0</b></div><div><strong>Final amount</strong><strong>'+money(t.amount)+'</strong></div></div><p class="sub">The server validates your current price, stock and credit before placing the order.</p>'}
function orderPayload(){const choice=$('deliveryChoice'),s=choice?.value===''?null:choice?._slots?.[Number(choice.value)];return {items:Object.entries(cart).map(([productId,quantity])=>({productId,quantity})),paymentType:document.querySelector('input[name="pay"]:checked')?.value||'COD',deliveryDate:s?.date||'',deliverySlot:s?.slot||'',deliveryAddress:vendor().address,area:vendor().area}}
function orderRequest(payload){const fingerprint=JSON.stringify({vendorId:vendor().vendorId,...payload});let saved=parse(storageGet('nel_b2b_v5_order_request'));if(!saved||saved.fingerprint!==fingerprint){saved={fingerprint,id:uid()};try{localStorage.setItem('nel_b2b_v5_order_request',JSON.stringify(saved))}catch(_){}}return saved.id}
let upiIntent=null;
async function confirmOrder(){if(confirming)return;if(!cartValid())return msg('Review your cart before ordering');if(!vendor().address)return msg('Add your delivery address in Account before ordering');confirming=true;const btn=$('confirmOrderBtn');btn.disabled=true;btn.textContent='Submitting…';const token=TOKEN,epoch=sessionEpoch,p=orderPayload();p.clientRequestId=orderRequest(p);
  try{if(p.paymentType==='UPI'){
      const key=JSON.stringify(p);if(!upiIntent||upiIntent.key!==key){const r=await rpc('prepareB2BUpiPaymentV916',[token,p]);if(TOKEN!==token||epoch!==sessionEpoch)return;upiIntent={...r,key,payload:p};}
      $('upiInfo').textContent='Pay '+money(upiIntent.amount)+' to '+upiIntent.upiName+' ('+upiIntent.upiId+'). Payment requires verification.';const uri=String(upiIntent.upiUri||'');if(!/^upi:\/\/pay\?/i.test(uri))throw new Error('Payment link unavailable. Choose COD or contact support.');$('openUpi').href=uri;show('upi');
    }else{const r=await rpc('placeB2BOrderV9',[token,p]);if(TOKEN!==token||epoch!==sessionEpoch)return;await orderSuccess(r,p)}}catch(e){msg(e.message)}finally{confirming=false;btn.disabled=false;btn.textContent='Confirm Order'}
}
async function submitUpi(){if(confirming||!upiIntent)return;const utr=$('utr').value.replace(/\s/g,'');if(!/^[A-Za-z0-9]{6,40}$/.test(utr))return msg('Enter the UTR / transaction number from your payment app');confirming=true;const btn=$('submitUpiBtn');btn.disabled=true;const token=TOKEN,epoch=sessionEpoch;
  try{const r=await rpc('submitB2BUpiOrderV916',[token,upiIntent.paymentId,utr,upiIntent.payload]);if(TOKEN!==token||epoch!==sessionEpoch)return;await orderSuccess(r,upiIntent.payload);upiIntent=null;$('utr').value=''}catch(e){msg(e.message)}finally{confirming=false;btn.disabled=false}
}
async function orderSuccess(r,p){if(!r?.success||!r.orderId)throw new Error('Order result unavailable. Retry with the same cart.');const qty=p.items.reduce((n,i)=>n+i.quantity,0);activeOrderId=r.orderId;cart={};selectedQty={};saveCart();$('confirmation').querySelector('.card').innerHTML='<p><b>Order ID:</b> #'+esc(r.orderId)+'</p><p><b>Total Amount:</b> '+money(r.amount)+'</p><p><b>Total Items:</b> '+qty+' units</p><p><b>Status:</b> '+esc(r.status||'Order Received')+'</p><p class="sub">'+(r.autoAccepted?'Accepted against available stock and delivery capacity.':r.paymentStatus==='VERIFICATION_PENDING'?'UPI payment is awaiting verification. Delivery will be scheduled after payment is verified.':'Your order has been received. Operations will confirm stock and schedule your delivery.')+'</p>'+(r.deliveryDate?'<p class="sub">Delivery: '+esc(r.deliveryDate+' · '+r.deliverySlot)+'</p>':'')+(r.deliveryOtp?'<p><b>Delivery OTP:</b> '+esc(r.deliveryOtp)+'</p><p class="sub">Share this only with your delivery partner when receiving the order.</p>':'');show('confirmation');msg('Order received · '+r.orderId);const fallback={orderId:r.orderId,amount:r.amount,status:r.status||'Order Received',paymentType:p.paymentType,paymentStatus:r.paymentStatus||'PENDING',orderedAt:new Date().toLocaleString('en-IN'),deliveryDate:r.deliveryDate||p.deliveryDate,deliverySlot:r.deliverySlot||p.deliverySlot,items:p.items.map(i=>({...i,productName:product(i.productId)?.productName||i.productId}))};DATA.orders=[fallback,...orders().filter(o=>o.orderId!==r.orderId)];render();void refresh(true)}
let trackEpoch=0;
async function openTrack(id){const o=orders().find(x=>x.orderId===id);if(!o)return msg('Order information is loading. Refresh My Orders.');activeOrderId=id;const epoch=++trackEpoch,token=TOKEN;$('track').querySelector('.simpleHead b').textContent='Track Order #'+o.orderId;const names=['Order Received','Confirmed','Packed','Out for Delivery','Delivered'],idx=names.findIndex(n=>n.toUpperCase()===o.status.toUpperCase());$('track').querySelector('.pad').innerHTML='<div class="timeline">'+names.map((n,i)=>'<div class="'+(i>idx?'off':'')+'"><b>'+((i<=idx)?'✓':'·')+'</b>'+esc(n)+'</div>').join('')+'</div><div class="card"><b>'+esc(o.status)+'</b><p class="sub">'+(o.deliveryDate?esc(o.deliveryDate+' · '+o.deliverySlot):'Delivery schedule pending')+'</p><p class="sub">'+esc(o.paymentType+' · '+(o.paymentStatus||'Pending'))+'</p><p class="sub">'+(o.items||[]).map(i=>esc(i.productName)+' × '+Number(i.quantity)).join('<br>')+'</p><b>'+money(o.amount)+'</b></div><div id="liveTracking" class="track" style="padding:16px;margin-top:10px;text-align:center">Loading delivery tracking…</div><button class="wide" data-invoice="'+encodeURIComponent(id)+'">View Invoice</button><button class="wide" onclick="openTrack(activeOrderId)">Refresh Tracking</button>';show('track');try{const t=await rpc('getVendorLiveTracking',[token,id]);if(epoch!==trackEpoch||TOKEN!==token||CURRENT!=='track')return;const valid=t.active&&Number.isFinite(t.lat)&&Number.isFinite(t.lng);$('liveTracking').innerHTML=valid?'<div><b>Delivery location updated</b><p class="sub">'+esc(t.updatedAt)+'<br>'+Number(t.stopsBefore||0)+' stops before you'+(t.eta?'<br>Planned ETA: '+esc(t.eta):'')+'</p><a class="cta" style="display:inline-block;text-decoration:none" href="https://www.google.com/maps?q='+encodeURIComponent(t.lat+','+t.lng)+'" target="_blank" rel="noopener">Open Delivery Map</a></div>':esc(t.message||'Live tracking is not available yet.');}catch(e){if(epoch===trackEpoch&&TOKEN===token&&CURRENT==='track')$('liveTracking').textContent=e.message}}
function schemeTab(benefits,b){const t=DATA?.target,pad=$('schemes').querySelector('.pad');pad.innerHTML='<div class="tabs"><button class="'+(!benefits?'on':'')+'" onclick="schemeTab(false)">Active Schemes</button><button class="'+(benefits?'on':'')+'" onclick="schemeTab(true)">My Benefits</button></div>'+(t?'<div class="card scheme"><div><h3>'+esc(t.name)+'</h3><p>'+esc(t.startDate+' – '+t.endDate)+'</p><p>'+Number(t.achievedQty||0)+' / '+Number(t.targetQty||0)+' units · '+Number(t.percent||0)+'%</p><strong>'+esc(t.rewardText||'See published eligibility rules')+'</strong><p class="sub">'+esc(t.status)+'</p>'+(benefits?'<p class="sub">Target progress does not by itself confirm that a benefit has been awarded. Contact support for fulfillment.</p>':'')+'</div><div class="reward">🎁</div></div>':'<div class="infoPanel"><b>'+ (benefits?'No benefit records published':'No active schemes published')+'</b><p>Eligible schemes and targets will appear here when available for your account.</p></div>')}
function renderProfile(force=false){const v=vendor();$('profilePhone').value=v.mobile||'';$('profilePhone').readOnly=true;if(force||CURRENT!=='profile')$('profile').querySelector('input:not(#profilePhone)').value=v.ownerName||'';const inputs=$('shop').querySelectorAll('input');if(force||CURRENT!=='shop')inputs[0].value=v.businessName||'';inputs[1].value=v.vendorId||'';$('account').querySelector('h3').textContent=v.businessName||'Business Partner';$('account').querySelector('h3 + .sub').textContent='Vendor ID: '+(v.vendorId||'');const hour=Number(new Intl.DateTimeFormat('en-IN',{hour:'numeric',hourCycle:'h23',timeZone:'Asia/Kolkata'}).format(new Date()));$('home').querySelector('.greet h2').textContent='Good '+(hour<12?'Morning':hour<17?'Afternoon':'Evening')+', '+(v.ownerName||'Partner').split(' ')[0]+' 👋';$('home').querySelector('.brand .sub').textContent=v.area||'Business Partner';$('address').querySelector('.pad').innerHTML='<div class="card"><b>'+esc(v.businessName||'My Shop')+'</b><p class="sub">'+esc(v.address||'No delivery address recorded')+'</p><p class="sub">Service area: '+esc(v.area||'Pending')+'</p></div><button class="wide" onclick="addAddress()">Edit Delivery Address</button><p class="sub">For a new shop location or service area, contact Support.</p>'}
async function saveAccount(p,button){if(button.disabled)return;button.disabled=true;const token=TOKEN,epoch=sessionEpoch;try{await rpc('saveB2BProfileV5',[token,p]);if(TOKEN!==token||epoch!==sessionEpoch)return;await refresh();msg('Changes saved');if(p.address)show('address')}catch(e){msg(e.message)}finally{button.disabled=false}}
function saveProfile(){const name=$('profile').querySelector('input:not(#profilePhone)').value.trim();if(!name)return msg('Enter the owner name');return saveAccount({ownerName:name},$('profile').querySelector('.wide'))}
function saveShop(){const name=$('shop').querySelector('input').value.trim();if(!name)return msg('Enter the business name');return saveAccount({businessName:name},$('shop').querySelector('.wide'))}
function addAddress(){$('addressText').value=vendor().address||'';show('addressEdit')}
function saveAddress(){const address=$('addressText').value.trim();if(!address)return msg('Enter the delivery address');return saveAccount({address},$('addressEdit').querySelector('.wide'))}
function renderPayments(){const v=vendor();$('payments').querySelector('.balance .sub').textContent='Credit Outstanding';$('payments').querySelector('.balance strong').textContent=money(v.outstanding);$('credit').querySelector('.pad').innerHTML='<div class="balance"><div class="sub">Approved Credit Limit</div><strong>'+money(v.creditLimit)+'</strong></div><div class="card" style="margin-top:10px"><div class="row"><span>Outstanding</span><b>'+money(v.outstanding)+'</b></div><div class="row" style="margin-top:10px"><span>Available Credit</span><b>'+money(v.availableCredit)+'</b></div><p class="sub">'+(v.paymentType==='CREDIT'?'Credit checkout is enabled within your available limit.':'Credit checkout is not enabled for this account.')+'</p></div><button class="wide" onclick="show(\'schemes\')">View Schemes & Eligibility</button>'}
function paymentHistory(label){$('historyTitle').textContent=label;const invoice=label==='Invoices & Bills',list=invoice?orders():DATA?.payments||[];$('historyList').innerHTML=list.map(o=>'<div class="orderCard"><b>#'+esc(o.orderId||o.paymentId)+'</b><p class="sub">'+esc(o.orderedAt||o.createdAt||'')+' · '+esc(o.paymentType||o.method||'')+' · '+esc(o.paymentStatus||o.status||'')+'</p><b>'+money(o.amount)+'</b>'+(invoice?'<button class="wide" data-invoice="'+encodeURIComponent(o.orderId)+'">Open Invoice</button>':'')+'</div>').join('')||'<div class="emptyState"><b>No records yet</b><p>Only recorded payments appear here. Cash collection may appear in your order payment status.</p></div>';show('history')}
function renderNotifications(){$('notifications').querySelector('.pad').innerHTML=orders().slice(0,10).map(o=>'<div class="notice"><b>Order #'+esc(o.orderId)+' · '+esc(o.status)+'</b><p>'+esc(o.orderedAt)+' · '+esc(o.paymentStatus||'Payment pending')+'</p></div>').join('')||'<div class="infoPanel"><b>No order updates yet</b><p>Your order activity will appear here.</p></div>'}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return msg('Voice is unavailable here. Please type your issue.');if(voice)return msg('Already listening');voice=new SR();voice.lang=$('voiceLang').value||navigator.language||'en-IN';voice.interimResults=false;voice.onstart=()=>msg('Listening…');const voiceToken=TOKEN;voice.onresult=e=>{if(CURRENT!=='support'||TOKEN!==voiceToken)return;$('issue').value=e.results[0][0].transcript;msg('Voice captured. Review the text.')};voice.onerror=()=>msg('Could not capture voice. Please type your issue.');voice.onend=()=>voice=null;try{voice.start()}catch(_){voice=null;msg('Voice could not start. Please type your issue.')}}
function aiDraft(){const t=$('issue').value.trim();if(!t)return msg('Speak or type your issue first');let c='Other';if(/damage|quality|bad|spoiled|broken/i.test(t))c='Quality Issue';else if(/late|delivery|driver|not delivered|eta/i.test(t))c='Delivery Issue';else if(/payment|upi|refund|charged|money/i.test(t))c='Payment Issue';else if(/order|quantity|missing|wrong item/i.test(t))c='Order Issue';else if(/app|login|screen|error/i.test(t))c='App Issue';$('cat').value=c;$('title').value=c==='Other'?'Support request':c;$('details').value=t;$('draft').classList.remove('hidden');msg('Draft prepared from your text. Review category, title and details.')}
let ticketRequest=null,ticketBusy=false;
async function submitTicket(){if(ticketBusy||$('draft').classList.contains('hidden'))return;const p={category:$('cat').value,title:$('title').value.trim(),details:$('details').value.trim()};if(!p.title||!p.details)return msg('Review ticket title and details');const key=JSON.stringify(p);if(ticketRequest?.key!==key)ticketRequest={key,id:uid()};p.clientRequestId=ticketRequest.id;ticketBusy=true;const btn=$('draft').querySelector('.wide');btn.disabled=true;const token=TOKEN,epoch=sessionEpoch;try{const r=await rpc('createB2BTicketV5',[token,p]);if(TOKEN!==token||epoch!==sessionEpoch)return;ticketRequest=null;$('draft').classList.add('hidden');$('issue').value='';msg('Ticket submitted · '+r.ticketId);await refresh(true)}catch(e){msg(e.message)}finally{ticketBusy=false;btn.disabled=false}}
function renderTickets(){$('tickets').innerHTML=(DATA?.tickets||[]).map(t=>'<div class="ticket"><b>#'+esc(t.ticketId)+' · '+esc(t.category)+'</b><p>'+esc(t.title)+': '+esc(t.details)+'</p><small>'+esc(t.status)+' · '+esc(t.createdAt)+'</small>'+(t.resolution?'<p>Response: '+esc(t.resolution)+'</p>':'')+'</div>').join('')||'<div class="ticket sub">No support tickets yet.</div>'}
async function invoice(id){const w=window.open('','_blank');if(!w)return msg('Allow pop-ups to open your invoice');w.opener=null;w.document.write('<p>Loading invoice…</p>');const token=TOKEN,epoch=sessionEpoch;try{const d=await rpc('getB2BInvoiceV91',[token,id]);if(TOKEN!==token||epoch!==sessionEpoch){w.close();return}const l=d.legal||{};w.document.open();w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+esc(d.invoiceNo)+'</title><style>body{font:14px Arial;margin:32px;color:#122017}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}@media print{button{display:none}}</style></head><body><h1>Native Elaneeru</h1><p>'+esc(l.legalName||'')+'</p><h2>'+esc(d.documentType)+'</h2><p>'+esc(d.invoiceNo)+' · '+esc(d.invoiceDate)+'</p><p>'+esc(d.partyName)+'<br>'+esc(d.address)+'<br>'+esc(d.mobile)+'</p><table><tr><th>Product</th><th>Quantity</th><th>Rate</th><th>Amount</th></tr>'+(d.items||[]).map(i=>'<tr><td>'+esc(i.productName)+'</td><td>'+Number(i.qty)+'</td><td>'+money(i.rate)+'</td><td>'+money(i.lineAmount)+'</td></tr>').join('')+'</table><h2>Total '+money(d.total)+'</h2><p>'+esc(d.paymentType)+'</p><p>Support: '+esc(l.supportPhone||'')+'</p><button onclick="print()">Print / Save PDF</button></body></html>');w.document.close()}catch(e){w.document.body.textContent=e.message;msg(e.message)}}
async function openLegal(){show('legal');$('legalInfo').textContent='Loading…';try{const l=await rpc('getCompliancePublicV91',[]);$('legalInfo').innerHTML=[['Legal entity',l.legalName],['Business address',l.businessAddress],['FSSAI',l.fssaiNo||'Application Pending'],['GST',l.gstin||'Not registered'],['Grievance Officer',l.grievanceOfficer],['Grievance email',l.grievanceEmail],['Support',l.supportPhone]].map(([k,v])=>'<div class="notice"><b>'+esc(k)+'</b><p>'+esc(v||'To be confirmed')+'</p></div>').join('')}catch(e){$('legalInfo').textContent=e.message}}
function updateNavigation(id){
  const nav=$('mainNavigation');if(!nav)return;
  nav.classList.toggle('hidden',!TOKEN||!DATA||id==='login'||id==='registration');
  const active=['home','products','cart','orders','account'].includes(id)?id:
    ['place','upi'].includes(id)?'cart':['confirmation','track'].includes(id)?'orders':
    id==='schemes'?'home':'account';
  nav.querySelectorAll('button').forEach(b=>{const selected=b.dataset.page===active;b.classList.toggle('on',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
}
function extraScreen(id,title,body,back='account'){if($(id))return;const s=document.createElement('section');s.id=id;s.className='screen hidden';s.innerHTML='<div class="simpleHead"><button class="back" onclick="show(\''+back+'\')">‹</button><b>'+title+'</b></div><div class="pad">'+body+'</div>';document.querySelector('.phone').append(s)}
function setup(){
  document.querySelector('.phone').addEventListener('error',e=>{const img=e.target;if(img.tagName!=='IMG'||!img.closest('#plist,#cartList,#bannerTrack')||img.dataset.fallback)return;img.dataset.fallback='1';img.src='../b2c/images/tender-coconut-v2.webp'},true);
  extraScreen('addressEdit','Delivery Address','<div class="field"><label for="addressText">Shop delivery address (same service area)</label><textarea id="addressText" maxlength="500"></textarea></div><button class="wide" onclick="saveAddress()">Save Address</button>','address');extraScreen('history','Transactions','<h3 id="historyTitle"></h3><div id="historyList"></div>','payments');extraScreen('credit','My Credit','', 'payments');extraScreen('legal','Legal & Food Safety','<div id="legalInfo"></div>','account');extraScreen('upi','Pay via UPI','<div class="card"><p id="upiInfo" class="sub"></p><a id="openUpi" class="wide" style="display:block;text-align:center;text-decoration:none" href="#">Open UPI App</a><div class="field" style="margin-top:15px"><label for="utr">UTR / Transaction Number</label><input id="utr" autocomplete="off" maxlength="40"></div><button id="submitUpiBtn" class="wide" onclick="submitUpi()">Submit Payment & Order</button><p class="sub">Submitting a UTR does not mark the payment as paid. Operations verifies it before fulfillment.</p></div>','place');
  document.querySelectorAll('.nav').forEach(n=>n.remove());
  document.querySelector('.phone').insertAdjacentHTML('beforeend','<nav id="mainNavigation" class="nav hidden" aria-label="Main navigation">'+[['home','⌂','Home'],['products','▦','Products'],['cart','🛒','Cart'],['orders','▣','Orders'],['account','♙','Account']].map(([id,icon,label])=>'<button data-page="'+id+'" onclick="show(\''+id+'\')"><span>'+icon+'</span>'+label+'</button>').join('')+'</nav>');
  $('products').querySelector('.pad').insertAdjacentHTML('afterbegin','<div class="mainSummary"><div><small>Available</small><b>—</b></div><div><small>MOQ From</small><b>—</b></div><div><small>Supply</small><b>Live catalogue</b></div></div>');$('products').querySelector('.pad').insertAdjacentHTML('beforeend','<div class="infoPanel"><b>Today’s Supply</b><p>Add the minimum quantity and increase using the product’s step. Availability is checked again at acceptance.</p></div>');
  $('orders').querySelector('.pad').insertAdjacentHTML('afterbegin','<div class="mainSummary"><div><small>Active</small><b>0 Orders</b></div><div><small>Delivered</small><b>0 Orders</b></div><div><small>Total Qty</small><b>0 units</b></div></div>');
  ['home','orders','products'].forEach(id=>$(id).querySelector(id==='home'?'.head':'.simpleHead').insertAdjacentHTML('beforeend','<button class="liveRefresh" aria-label="Refresh account" onclick="refresh()">⟳</button>'));
  $('profilePhone').readOnly=true;$('profilePhone').parentElement.insertAdjacentHTML('afterend','<div class="lockedNote">Registered mobile number. Contact Support if it needs to change.</div>');
  const menu=$('account').querySelector('.menu');menu.insertAdjacentHTML('beforeend','<button id="installBtn" class="hidden" onclick="installApp()"><div><span class="mi">↓</span>Install App</div><span>›</span></button><button onclick="openLegal()"><div><span class="mi">ⓘ</span>Legal & Food Safety</div><span>›</span></button><button onclick="logout()"><div><span class="mi">↪</span>Logout</div><span>›</span></button>');
  $('home').querySelector('.quick button:nth-child(5)').onclick=()=>show('credit');$('payments').querySelector('.menu button:nth-child(2)').onclick=()=>show('credit');$('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});$('loginPhone').addEventListener('keydown',e=>{if(e.key==='Enter')goPin()});
  document.addEventListener('click',e=>{const b=e.target.closest('button,[data-dot]');if(!b)return;const d=b.dataset;
    if(d.qty)q(decodeURIComponent(d.qty),Number(d.dir));if(d.cartQty)q(decodeURIComponent(d.cartQty),Number(d.dir),true);if(d.add)add(decodeURIComponent(d.add));if(d.remove)removeItem(decodeURIComponent(d.remove));if(d.track)openTrack(decodeURIComponent(d.track));if(d.reorder)reorder(decodeURIComponent(d.reorder));if(d.invoice)invoice(decodeURIComponent(d.invoice));if(d.banner!==undefined)bannerAction(Number(d.banner));if(d.dot!==undefined)setBanner(Number(d.dot));
  });document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.dataset.dot!==undefined)setBanner(Number(e.target.dataset.dot))});
  let sx=0;$('bannerViewport').addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});$('bannerViewport').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>35)setBanner(bi+(dx<0?1:-1))},{passive:true});setInterval(()=>{if(CURRENT==='home'&&document.visibilityState==='visible')setBanner(bi+1)},6000);
}
async function restoreSession(){const saved=parse(storageGet('nel_b2b_green_session'));let token=storageGet('nel_b2b_token')||storageGet('nel_b2b_token',sessionStorage)||storageGet('nel_b2b_approved_token')||saved?.token;const epoch=sessionEpoch;if(token)sessionRestoreUi(true);
  if(!token)try{const db=await window.NEL_B2B_DB?.get('sessionToken');token=typeof db==='string'?db:db?.token}catch(_){}
  if(epoch!==sessionEpoch||!token)return;sessionRestoreUi(true);TOKEN=token;if(await refresh()){persistSession();show('home')}
}
async function installApp(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else msg('Open your browser menu and choose Add to Home screen')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').classList.remove('hidden')});window.addEventListener('appinstalled',()=>$('installBtn').classList.add('hidden'));
window.addEventListener('online',()=>{msg('Connection restored');if(TOKEN)refresh(true)});window.addEventListener('offline',()=>msg('You are offline. Orders require a connection.'));
let lastRefresh=Date.now();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&TOKEN&&Date.now()-lastRefresh>60000){lastRefresh=Date.now();refresh(true)}});
// Update the same PWA identity and scope; defer reload during a submitted order.
if('serviceWorker' in navigator){let hadController=!!navigator.serviceWorker.controller;let reloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController&&!reloaded){reloaded=true;if(confirming){msg('App update ready. Reopen after your order finishes.');return}location.reload()}});navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>{r.update();setInterval(()=>r.update(),60000)}).catch(()=>{})}
setup();restoreSession();
