const CACHE='native-elaneeru-business-install-v9.8.7';
const SHELL=['./','./index.html','./config.js','./idb-v1.js','./ui-v113.js','./order-sync-v1.js','./separate-links.js','./session-v960.js','./session-v985.js','./session-guard-v980.js','./production-fixes-v990.js','./payment-upi-v916.js','./runtime-guard-v918.js','./vendor-growth-v100.js','./update-notifier.js','./analytics-v981.js','./coming-soon-banner-v986.js','./manifest.webmanifest','./icons/icon-192.png?v=984','./icons/icon-512.png?v=984'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function networkFirst(request,fallback){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy)).catch(()=>{})}return response}catch(err){const cached=await caches.match(request);if(cached)return cached;if(fallback){const page=await caches.match(fallback);if(page)return page}throw err}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy)).catch(()=>{})}return response}
async function staleWhileRevalidate(request,fallback){const cached=await caches.match(request),refresh=networkFirst(request).catch(()=>null);if(cached){refresh.catch(()=>{});return cached}const response=await refresh;if(response)return response;if(fallback){const page=await caches.match(fallback);if(page)return page}throw new Error('offline')}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(staleWhileRevalidate(request,'./index.html'));return}const critical=/\/(?:config|idb-v1|ui-v113|order-sync-v1|separate-links|session-v960|session-v985|session-guard-v980|production-fixes-v990|payment-upi-v916|runtime-guard-v918|vendor-growth-v100|update-notifier|coming-soon-banner-v986)\.js$/;if(critical.test(url.pathname)||url.pathname.endsWith('/manifest.webmanifest')){event.respondWith(staleWhileRevalidate(request));return}event.respondWith(cacheFirst(request))});
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){if('focus'in c)return c.focus()}return clients.openWindow('./')}))});
