'use strict';
const $=id=>document.getElementById(id);
const P=[['Normal Coconut (Grade A)',44,50],['Mixed Coconuts',42,50],['Pollachi Coconut',55,50]];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>'₹'+Number(x||0).toLocaleString('en-IN');
let cart={},bi=0,sx=0,category='All',orderFilter='All',selectedQty={},activeOrderId='NE985632',confirming=false,voice=null;
let state={phone:'9876543210',owner:'Ramesh Kumar',shop:'Sri Venkatesh Coconut Stall',address:'Jayanagar, Bangalore - 560011',orders:[],tickets:[]};
const sampleOrders=()=>[{id:'NE985632',date:'5 Oct 2026',status:'Out for Delivery',items:{0:100,1:50,2:50},payment:'COD',address:state.address},{id:'NE984901',date:'2 Oct 2026',status:'Delivered',items:{0:150},payment:'COD',address:state.address}];
function totals(items=cart){return Object.entries(items).reduce((a,[i,n])=>({qty:a.qty+n,amount:a.amount+n*P[i][1]}),{qty:0,amount:0})}
function storageKey(){return 'ne_demo_v5_'+state.phone}
function save(){try{localStorage.setItem(storageKey(),JSON.stringify({...state,cart}));}catch(_){}}
function load(phone){state={phone,owner:'Ramesh Kumar',shop:'Sri Venkatesh Coconut Stall',address:'Jayanagar, Bangalore - 560011',orders:[],tickets:[]};cart={};try{const saved=JSON.parse(localStorage.getItem(storageKey())||'null');if(saved&&saved.phone===phone){state={...state,...saved};cart=saved.cart||{}}}catch(_){};cart=Object.fromEntries(Object.entries(cart).filter(([i,n])=>P[i]&&Number.isInteger(n)&&n>=P[i][2]));if(!Array.isArray(state.orders)||!state.orders.length)state.orders=sampleOrders();if(!Array.isArray(state.tickets))state.tickets=[];activeOrderId=state.orders[0].id;selectedQty={};}
function msg(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(msg.timer);msg.timer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function show(id){const screen=$(id);if(!screen?.classList.contains('screen'))return msg('This page is unavailable');if((id==='place'||id==='confirmation')&&!Object.keys(cart).length&&id!=='confirmation')return msg('Add products before checkout');document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('hidden',x!==screen));screen.scrollTop=0;if(id==='products')renderProducts();if(id==='cart')renderCart();if(id==='home')renderBanners();if(id==='orders')renderOrders();if(id==='account'||id==='profile'||id==='shop'||id==='address')refreshProfile();if(id==='payments')refreshPayments();}
function goPin(){const p=$('loginPhone').value.replace(/\D/g,'');if(p.length!==10)return msg('Enter a valid 10-digit mobile number');$('loginPhone').value=p;$('phoneEcho').textContent='+91 '+p;$('phoneStep').classList.add('hidden');$('pinStep').classList.remove('hidden');$('loginPin').focus()}
function backPhone(){$('pinStep').classList.add('hidden');$('phoneStep').classList.remove('hidden');$('loginPin').value=''}
function doLogin(){if(!/^\d{10}$/.test($('loginPhone').value))return backPhone();if($('loginPin').value!=='1234')return msg('Demo PIN is 1234');load($('loginPhone').value);refreshDemo();show('home');msg('Demo mode — orders and tickets stay on this device.')}
function logoutDemo(){if(voice)voice.abort();save();cart={};selectedQty={};$('loginPin').value='';backPhone();show('login')}
function registerDemo(){show('registration')}
function saveRegistration(){const phone=$('regPhone').value.trim(),owner=$('regOwner').value.trim(),shop=$('regShop').value.trim();if(!/^\d{10}$/.test(phone)||!owner||!shop)return msg('Enter your name, shop and 10-digit mobile');load(phone);state.owner=owner;state.shop=shop;save();$('loginPhone').value=phone;show('login');backPhone();msg('Demo registration saved locally. Use PIN 1234.')}
const banners=[{c:'a',h:'Fresh Coconuts for a Healthier Bangalore',p:'Better Price. Daily Supply. Grow Together.',go:'products',b:'Order Now'},{c:'b',h:'Reliable Supply for Your Shop',p:'Plan stock better with dependable delivery.',go:'products',b:'View Products'},{c:'c',h:'Benefits Built for Local Vendors',p:'Schemes, payments and credit eligibility in one place.',go:'schemes',b:'View Benefits'}];
function renderBanners(){if(!$('bannerTrack').children.length){$('bannerTrack').innerHTML=banners.map(x=>`<div class="hero ${x.c}"><h1>${x.h}</h1><p>${x.p}</p><button class="cta" onclick="show('${x.go}')">${x.b}</button><img src="../b2c/images/tender-coconut-v2.webp" alt="Tender coconut" decoding="async"></div>`).join('');$('bannerDots').innerHTML=banners.map((_,i)=>`<i role="button" tabindex="0" aria-label="Banner ${i+1}" onclick="setBanner(${i})" onkeydown="if(event.key==='Enter')setBanner(${i})"></i>`).join('')}setBanner(bi)}
function setBanner(i){bi=(i+banners.length)%banners.length;$('bannerTrack').style.transform=`translateX(-${bi*100}%)`;$('bannerDots').querySelectorAll('i').forEach((d,j)=>d.classList.toggle('on',j===bi))}
$('bannerViewport').addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});$('bannerViewport').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>35)setBanner(bi+(dx<0?1:-1))},{passive:true});
setInterval(()=>{if(document.visibilityState==='visible'&&!$('home').classList.contains('hidden'))setBanner(bi+1)},6000);
function filterProducts(c,button){category=c;document.querySelectorAll('#products .chip').forEach(b=>b.classList.toggle('on',b===button));renderProducts()}
function renderProducts(){const search=($('productSearch')?.value||'').trim().toLowerCase();$('plist').innerHTML=P.map((p,i)=>({p,i})).filter(({p})=>(category==='All'||p[0].includes(category))&&p[0].toLowerCase().includes(search)).map(({p,i})=>`<div class="product"><img src="../b2c/images/tender-coconut-v2.webp" alt="${esc(p[0])}" loading="lazy"><div><div class="pname">${esc(p[0])}</div><div class="price">${money(p[1])} / piece</div><div class="moq">MOQ: ${p[2]} pieces</div><div class="qty"><button aria-label="Decrease ${esc(p[0])}" onclick="q(${i},-50)">−</button><b id="q${i}">${selectedQty[i]||cart[i]||p[2]}</b><button aria-label="Increase ${esc(p[0])}" onclick="q(${i},50)">+</button></div></div><button class="add" onclick="add(${i})">${cart[i]?'Update':'Add'}</button></div>`).join('')||'<div class="card sub">No products match your search.</div>'}
function q(i,d){if(!P[i])return;selectedQty[i]=Math.max(P[i][2],Number($('q'+i).textContent)+d);$('q'+i).textContent=selectedQty[i]}
function add(i){if(!P[i])return;const n=Number($('q'+i)?.textContent);if(!Number.isInteger(n)||n<P[i][2])return msg('Start with the minimum quantity');cart[i]=n;selectedQty[i]=n;save();renderCart();msg('Added '+n+' pieces to cart')}
function renderCart(){const t=totals();$('cartList').innerHTML=Object.entries(cart).map(([i,n])=>`<div class="cartRow"><img src="../b2c/images/tender-coconut-v2.webp" alt="${esc(P[i][0])}"><div><div class="pname">${esc(P[i][0])}</div><div class="price">${money(P[i][1])} / piece</div><div class="qty"><button onclick="cq(${i},-50)">−</button><b>${n}</b><button onclick="cq(${i},50)">+</button></div><button class="chip" onclick="removeItem(${i})">Remove</button></div><b>${money(n*P[i][1])}</b></div>`).join('')||'<div class="card">Your cart is empty.</div>';$('tq').textContent=t.qty+' pieces';$('ta').textContent=money(t.amount);$('checkoutBtn').disabled=!t.qty;$('cartSummary').classList.toggle('hidden',!t.qty)}
function cq(i,d){if(!P[i]||!cart[i])return;cart[i]=Math.max(P[i][2],cart[i]+d);selectedQty[i]=cart[i];save();renderCart()}
function removeItem(i){delete cart[i];delete selectedQty[i];save();renderCart()}
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
function beginCheckout(){if(!totals().qty)return msg('Add products before checkout');const cards=$('place').querySelectorAll('.card');cards[0].querySelector('p').textContent=state.shop+' • '+state.address;cards[1].querySelector('p').textContent=tomorrow();cards[2].innerHTML='<b>Payment Method</b><p style="font-size:10px"><label><input type="radio" name="pay" value="COD" checked> Cash on Delivery (COD)</label></p><p style="font-size:10px"><label><input type="radio" name="pay" value="UPI"> UPI — demo only</label></p><p class="sub">Credit is not enabled. Eligibility schemes will be published separately.</p>';show('place')}
function confirmOrder(){if(confirming)return;const t=totals();if(!t.qty)return msg('Cart is empty');confirming=true;try{const o={id:'NE'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,4).toUpperCase(),date:new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}),status:'Confirmed',items:{...cart},payment:document.querySelector('input[name="pay"]:checked')?.value||'COD',address:state.address};state.orders.unshift(o);activeOrderId=o.id;const ps=$('confirmation').querySelector('.card').querySelectorAll('p');ps[0].innerHTML='<b>Order ID:</b> #'+esc(o.id);ps[1].innerHTML='<b>Total Amount:</b> '+money(t.amount);ps[2].innerHTML='<b>Total Items:</b> '+t.qty+' pieces';cart={};selectedQty={};save();refreshDemo();show('confirmation');msg('Demo order saved locally — no supply order or payment was sent.')}finally{confirming=false}}
function filterOrders(f,b){orderFilter=f;document.querySelectorAll('#orders .orderTabs .chip').forEach(x=>x.classList.toggle('on',x===b));renderOrders()}
function renderOrders(){const pad=$('orders').querySelector('.pad');pad.querySelectorAll(':scope > .orderCard').forEach(x=>x.remove());const list=state.orders.filter(o=>orderFilter==='All'||(orderFilter==='Processing'&&['Confirmed','Packed'].includes(o.status))||(orderFilter==='In Transit'&&o.status==='Out for Delivery')||orderFilter===o.status);let host=$('orderList');if(!host){host=document.createElement('div');host.id='orderList';pad.querySelector('.orderTabs').after(host)}host.innerHTML=list.map(o=>{const t=totals(o.items);return `<div class="orderCard"><div class="row"><div><b>#${esc(o.id)}</b><div class="sub">${esc(o.date)} • ${t.qty} pieces</div></div><span class="pill">${esc(o.status)}</span></div><div class="row" style="margin-top:9px"><div class="amt">${money(t.amount)}</div><button class="cta" onclick="openTrack('${o.id}')">View details ›</button></div>${o.status==='Delivered'?`<button class="wide" onclick="reorder('${o.id}')">Reorder</button>`:''}</div>`}).join('')||'<div class="card sub">No orders in this category.</div>';const summary=pad.querySelector('.mainSummary');if(summary){const b=summary.querySelectorAll('b');b[0].textContent=state.orders.filter(o=>o.status!=='Delivered').length+' Orders';b[1].textContent=state.orders.filter(o=>o.status==='Delivered').length+' Orders';b[2].textContent=state.orders.reduce((n,o)=>n+totals(o.items).qty,0)+' pcs'}}
function reorder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;cart={...o.items};selectedQty={...cart};save();show('cart');msg('Reorder uses current demo prices.')}
function openTrack(id){const o=state.orders.find(x=>x.id===id);if(!o)return msg('Order not found');activeOrderId=id;$('track').querySelector('.simpleHead b').textContent='Track Order #'+o.id;const step=['Confirmed','Packed','Out for Delivery','Delivered'].indexOf(o.status);$('track').querySelectorAll('.timeline div').forEach((x,i)=>x.classList.toggle('off',i>step));$('track').querySelector('.track').innerHTML=o.status==='Out for Delivery'?'Demo delivery preview<br>Sample ETA: 45 minutes':o.status==='Delivered'?'Delivered — demo order':'Demo order confirmed<br>Delivery schedule pending';show('track')}
function schemeTab(benefits,button){document.querySelectorAll('#schemes .tabs button').forEach(b=>b.classList.toggle('on',b===button));document.querySelectorAll('#schemes .scheme').forEach(c=>c.classList.toggle('hidden',benefits));let box=$('benefitSummary');if(!box){box=document.createElement('div');box.id='benefitSummary';box.className='card';$('schemes').querySelector('.tabs').after(box)}box.classList.toggle('hidden',!benefits);box.innerHTML='<b>No benefits awarded yet</b><p class="sub">Sample schemes do not enable credit. Native Elaneeru will publish the eligibility rules.</p>'}
function refreshProfile(){$('profilePhone').value=state.phone;$('profilePhone').readOnly=true;$('profile').querySelector('input:not(#profilePhone)').value=state.owner;$('shop').querySelector('input').value=state.shop;$('account').querySelector('h3').textContent=state.shop;$('address').querySelector('.card .sub').textContent=state.address;const hour=new Date().getHours();$('home').querySelector('.greet h2').textContent='Good '+(hour<12?'Morning':hour<17?'Afternoon':'Evening')+', '+state.owner.split(' ')[0]+' 👋';}
function saveProfile(){const name=$('profile').querySelector('input:not(#profilePhone)').value.trim();if(!name)return msg('Enter the owner name');state.owner=name;save();refreshProfile();msg('Profile saved in this demo')}
function saveShop(){const name=$('shop').querySelector('input').value.trim();if(!name)return msg('Enter the business name');state.shop=name;save();refreshProfile();msg('Shop details saved in this demo')}
function addAddress(){show('addressEdit');$('addressText').value=state.address}
function saveAddress(){const address=$('addressText').value.trim();if(!address)return msg('Enter the delivery address');state.address=address;save();show('address');msg('Delivery address saved in this demo')}
function refreshPayments(){$('payments').querySelector('.balance .sub').textContent='Outstanding in this demo';$('payments').querySelector('.balance strong').textContent=money(state.orders.filter(o=>o.payment==='COD'&&o.status!=='Delivered').reduce((n,o)=>n+totals(o.items).amount,0));}
function paymentHistory(label){show('history');$('historyTitle').textContent=label;$('historyList').innerHTML=state.orders.map(o=>`<div class="orderCard"><b>#${esc(o.id)}</b><p class="sub">${esc(o.date)} • ${esc(o.payment)} • ${o.payment==='UPI'?'Demo payment — unverified':'Cash payment pending'}</p><b>${money(totals(o.items).amount)}</b></div>`).join('')||'<div class="card">No transactions yet.</div>'}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return msg('Voice is unavailable here. Please type your issue.');if(voice)return msg('Already listening');voice=new SR();voice.lang=$('voiceLang').value||navigator.language||'en-IN';voice.interimResults=false;voice.onstart=()=>msg('Listening…');voice.onresult=e=>{$('issue').value=e.results[0][0].transcript;msg('Voice captured. Review it before preparing your ticket.')};voice.onerror=()=>msg('Could not capture voice. Please type your issue.');voice.onend=()=>voice=null;try{voice.start()}catch(_){voice=null;msg('Voice could not start. Please type your issue.')}}
function aiDraft(){const t=$('issue').value.trim();if(!t)return msg('Speak or type your issue first');let c='Other',ti='Support request';if(/damage|quality|bad|spoiled|broken/i.test(t)){c='Quality Issue';ti='Damaged coconuts in delivered order'}else if(/late|delivery|driver|not delivered|eta/i.test(t)){c='Delivery Issue';ti='Delivery issue with recent order'}else if(/payment|upi|refund|charged|money/i.test(t)){c='Payment Issue';ti='Payment issue'}else if(/order|quantity|missing|wrong item/i.test(t)){c='Order Issue';ti='Order issue'}else if(/app|login|screen|error|not opening/i.test(t)){c='App Issue';ti='App issue'}$('cat').value=c;$('title').value=ti;$('details').value=t;$('draft').classList.remove('hidden');msg('Demo assistant prepared a draft. Please review it.')}
function submitTicket(){if($('draft').classList.contains('hidden'))return;const title=$('title').value.trim(),details=$('details').value.trim();if(!title||!details)return msg('Review ticket title and details first');const t={id:'NE-TKT-'+Date.now().toString(36).toUpperCase(),category:$('cat').value,title,details};state.tickets.unshift(t);save();renderTickets();$('draft').classList.add('hidden');$('issue').value='';msg('Demo ticket saved locally: '+t.id)}
function renderTickets(){$('tickets').innerHTML=state.tickets.map(t=>`<div class="ticket"><b>#${esc(t.id)} • ${esc(t.category)}</b><p>${esc(t.title)}: ${esc(t.details)}</p><small>Open • Demo ticket saved on this device</small></div>`).join('')||'<div class="ticket sub">No tickets created in this demo.</div>'}
function refreshDemo(){refreshDelivery();refreshProfile();renderProducts();renderCart();renderOrders();renderTickets();refreshPayments()}
function extraScreen(id,title,body,back='account'){const section=document.createElement('section');section.id=id;section.className='screen hidden';section.innerHTML=`<div class="simpleHead"><button class="back" onclick="show('${back}')">‹</button><b>${title}</b></div><div class="pad">${body}</div>`;document.querySelector('.phone').appendChild(section)}
extraScreen('registration','Demo Vendor Registration','<p class="sub">Demo only — this does not register a live vendor.</p><div class="field"><label>Owner Name</label><input id="regOwner"></div><div class="field"><label>Business Name</label><input id="regShop"></div><div class="field"><label>Mobile Number</label><input id="regPhone" inputmode="numeric" maxlength="10"></div><button class="wide" onclick="saveRegistration()">Save Demo Registration</button>','login');
extraScreen('addressEdit','Delivery Address','<div class="field"><label>Shop delivery address</label><textarea id="addressText"></textarea></div><button class="wide" onclick="saveAddress()">Save Address</button>','address');
extraScreen('history','Transactions','<h3 id="historyTitle"></h3><div id="historyList"></div>','payments');
$('account').querySelector('.menu').insertAdjacentHTML('beforeend','<button onclick="logoutDemo()"><div><span class="mi">↪</span>Logout</div><span>›</span></button>');
$('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});$('loginPhone').addEventListener('keydown',e=>{if(e.key==='Enter')goPin()});
load('9876543210');refreshDemo();renderBanners();

function refreshDelivery(){const o=state.orders.find(x=>x.status!=='Delivered');const card=$('home').querySelector('.delivery');if(!o){card.classList.add('hidden');return}card.classList.remove('hidden');activeOrderId=o.id;card.querySelector('.sub').textContent='Order #'+o.id;card.querySelector('.pill').textContent=o.status.toUpperCase();const b=card.querySelectorAll('.meta b');b[0].textContent=o.status==='Out for Delivery'?'45 mins (demo)':'Pending';b[1].textContent=totals(o.items).qty+' pcs';b[2].textContent=o.status==='Out for Delivery'?'Ramesh':'Unassigned';}

// Public sample-data preview. This app has no production authentication.
if(new URLSearchParams(location.search).get('preview')==='1')show('home');
