const products=[
{id:'P001',name:'A Grade Fresh Coconut',price:44,moq:100,step:50,stock:'In Stock',icon:'🥥'},
{id:'P002',name:'Mixed Coconut',price:42,moq:100,step:50,stock:'In Stock',icon:'🥥'},
{id:'P003',name:'Pollachi Premium',price:55,moq:100,step:50,stock:'Low Stock',icon:'🌴'}
];
const state={route:'home',cart:{}};
const app=document.getElementById('app');
const cartSheet=document.getElementById('cartSheet');

function money(n){return `₹${Number(n).toLocaleString('en-IN')}`}
function setRoute(route){state.route=route;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));render();window.scrollTo({top:0,behavior:'smooth'})}
function addProduct(id){const p=products.find(x=>x.id===id);if(!state.cart[id]) state.cart[id]=p.moq; else state.cart[id]+=p.step;renderCart();openCart()}
function adjust(id,dir){const p=products.find(x=>x.id===id);let next=(state.cart[id]||p.moq)+dir*p.step;if(next<p.moq){delete state.cart[id]}else state.cart[id]=next;renderCart()}
function cartTotal(){return Object.entries(state.cart).reduce((s,[id,q])=>{const p=products.find(x=>x.id===id);return s+p.price*q},0)}
function openCart(){renderCart();cartSheet.classList.add('open');cartSheet.setAttribute('aria-hidden','false')}
function closeCart(){cartSheet.classList.remove('open');cartSheet.setAttribute('aria-hidden','true')}
function productCards(){return `<div class="cards">${products.map(p=>`<article class="product-card"><div class="product-visual"><span class="stock-pill">${p.stock}</span>${p.icon}</div><h3>${p.name}</h3><div class="subtle">MOQ ${p.moq} • Step ${p.step}</div><div class="price-row"><span class="price">${money(p.price)}</span><button class="add-btn" onclick="addProduct('${p.id}')">Add</button></div></article>`).join('')}</div>`}
function home(){return `<section class="page"><div class="hero"><div class="eyebrow" style="color:#bff0d2">FRESH SUPPLY • BETTER MARGINS</div><h1>Fresh coconuts for your business, every day.</h1><p>Order the right quantity, track delivery, and grow your shop with Native Elaneeru.</p><div class="hero-actions"><button class="primary-btn" onclick="setRoute('products')">Order Fresh Stock</button><button class="ghost-btn" onclick="openCart()">View Cart</button></div></div><div class="section-head"><h2>Today’s products</h2><button onclick="setRoute('products')">View all</button></div>${productCards()}<div class="section-head"><h2>For your business</h2></div><div class="banner"><div><h3>Complete your target. Unlock benefits.</h3><p>Targets and rewards will only appear when approved for your vendor account.</p></div><div class="emoji">🎁</div></div><div class="section-head"><h2>Quick view</h2></div><div class="stat-grid"><div class="info-card"><strong>1</strong><small>Active order</small></div><div class="info-card"><strong>0</strong><small>Live schemes</small></div><div class="info-card"><strong>COD</strong><small>Current payment</small></div></div></section>`}
function productsPage(){return `<section class="page"><h1 class="screen-title">Fresh Products</h1><p class="screen-sub">Prices, MOQ and visibility will come from your commercial control sheet.</p>${productCards()}</section>`}
function orders(){return `<section class="page"><h1 class="screen-title">My Orders</h1><p class="screen-sub">Clear order status, amount payable and delivery progress.</p><div class="list"><article class="order-card"><div class="order-top"><div><strong>Order #NE1024</strong><div class="subtle">300 coconuts • ${money(13200)}</div></div><span class="status">Out for delivery</span></div><div class="tracking"><div class="track-node done"><div class="dot"></div>Confirmed</div><div class="track-node done"><div class="dot"></div>Packed</div><div class="track-node done"><div class="dot"></div>Dispatched</div><div class="track-node"><div class="dot"></div>Delivered</div></div></article><article class="order-card"><div class="order-top"><div><strong>Order #NE1018</strong><div class="subtle">200 coconuts • ${money(8800)}</div></div><span class="status">Delivered</span></div></article></div></section>`}
function rewards(){return `<section class="page"><h1 class="screen-title">Schemes & Growth</h1><p class="screen-sub">Only Native Elaneeru-approved schemes and customer targets will appear here.</p><div class="list"><article class="reward-card"><h3>Example target preview</h3><div class="subtle">This is a UI placeholder only — not active for customers.</div><div class="progress"><span style="width:62%"></span></div><strong>1,860 / 3,000 coconuts</strong><p class="subtle">Possible reward: Native Elaneeru umbrella</p></article><article class="reward-card"><h3>Credit</h3><div class="subtle">Credit is currently not enabled. It will appear only for approved vendors when you activate it.</div></article></div></section>`}
function account(){return `<section class="page"><h1 class="screen-title">Account</h1><p class="screen-sub">Vendor profile, payments, notifications and support.</p><div class="account-card"><div class="account-row"><span>Vendor Profile</span><b>›</b></div><div class="account-row"><span>Payment Methods</span><b>COD / UPI</b></div><div class="account-row"><span>Delivery Address</span><b>›</b></div><div class="account-row"><span>Notifications</span><b>›</b></div><div class="account-row"><span>Help & Support</span><b>›</b></div></div></section>`}
function render(){app.innerHTML=state.route==='home'?home():state.route==='products'?productsPage():state.route==='orders'?orders():state.route==='rewards'?rewards():account()}
function renderCart(){const rows=Object.entries(state.cart);document.getElementById('cartItems').innerHTML=rows.length?rows.map(([id,q])=>{const p=products.find(x=>x.id===id);return `<div class="cart-line"><div><strong>${p.name}</strong><div class="subtle">${money(p.price)} × ${q}</div></div><div class="qty"><button onclick="adjust('${id}',-1)">−</button><strong>${q}</strong><button onclick="adjust('${id}',1)">+</button></div></div>`}).join(''):'<p class="subtle">Your cart is empty.</p>';document.getElementById('cartTotal').textContent=money(cartTotal())}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setRoute(b.dataset.route)));
document.getElementById('closeCart').addEventListener('click',closeCart);
document.getElementById('notifBtn').addEventListener('click',()=>alert('Notifications will be driven by approved banners and business messages.'));
document.getElementById('placeOrderBtn').addEventListener('click',()=>{if(!Object.keys(state.cart).length)return alert('Add a product first.');alert('Approval build: order flow UI is working. Backend submission will be connected after your UI sign-off.');closeCart();setRoute('orders')});
render();
