/** Native Elaneeru V9.4.7 — read-only B2B Customer 360. */
const V947_C360_VERSION='9.4.7';

function v947Date_(v){const d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?null:d;}
function v947First_(row,names){for(var i=0;i<names.length;i++){var v=row&&row[names[i]];if(v!==''&&v!=null)return v;}return '';}
function v947Upper_(v){return s_(v).toUpperCase();}
function v947OrderDate_(o){return v947First_(o,['Ordered At','Created At','Order Date','Date']);}
function v947ReturnLike_(s){s=v947Upper_(s);return s.indexOf('RETURN')>=0||s.indexOf('REFUND')>=0;}
function v947Cancelled_(s){return v947Upper_(s).indexOf('CANCEL')>=0;}
function v947Delivered_(s){return v947Upper_(s).indexOf('DELIVER')>=0;}

function searchCustomer360V947(email,pin,query){
  v948RequireCustomer360_(email,pin);
  var q=s_(query).toLowerCase(),vendors=rows_(V8.SHEETS.B2B_VENDORS),orders=rows_(V8.SHEETS.B2B_ORDERS),stats={};
  orders.forEach(function(o){var id=s_(o['Vendor ID']);if(!id)return;var x=stats[id]||(stats[id]={count:0,value:0,last:null});x.count++;if(!v947Cancelled_(o.Status))x.value+=n_(v947First_(o,['Total Amount','Order Total','Amount']));var d=v947Date_(v947OrderDate_(o));if(d&&(!x.last||d>x.last))x.last=d;});
  var matched=vendors.filter(function(v){if(!q)return true;return ['Vendor ID','Business Name','Owner Name','Mobile','WhatsApp','Area','Pincode'].some(function(k){return s_(v[k]).toLowerCase().indexOf(q)>=0;});}).slice(0,50);
  return {success:true,version:V947_C360_VERSION,vendors:matched.map(function(v){var id=s_(v['Vendor ID']),x=stats[id]||{};return {vendorId:id,businessName:s_(v['Business Name']),ownerName:s_(v['Owner Name']),mobile:digits_(v.Mobile),area:s_(v.Area),pincode:s_(v.Pincode),status:s_(v.Status),orderCount:x.count||0,lifetimeValue:x.value||0,lastOrder:x.last?fmtDT_(x.last):''};})};
}

function getCustomer360ProfileV947(email,pin,vendorId){
  v948RequireCustomer360_(email,pin);vendorId=s_(vendorId);if(!vendorId)throw new Error('Vendor ID is required.');
  var vendor=find_(V8.SHEETS.B2B_VENDORS,'Vendor ID',vendorId);if(!vendor)throw new Error('B2B vendor not found.');
  var allOrders=rows_(V8.SHEETS.B2B_ORDERS).filter(function(o){return s_(o['Vendor ID'])===vendorId;});
  var orderIds={};allOrders.forEach(function(o){orderIds[s_(o['Order ID'])]=true;});
  var itemsByOrder={};rows_(V8.SHEETS.B2B_ORDER_ITEMS).forEach(function(i){var oid=s_(i['Order ID']);if(!orderIds[oid])return;(itemsByOrder[oid]||(itemsByOrder[oid]=[])).push({itemId:s_(i['Item ID']),productId:s_(i['Product ID']),productName:s_(i['Product Name']),quantity:n_(i.Quantity),unit:s_(i.Unit),unitPrice:n_(i['Unit Price']),lineAmount:n_(i['Line Amount']),pickedQuantity:n_(i['Picked Qty']),deliveredQuantity:n_(i['Delivered Qty']),status:s_(i.Status)});});
  allOrders.sort(function(a,b){return (v947Date_(v947OrderDate_(b))||0)-(v947Date_(v947OrderDate_(a))||0);});
  var orders=allOrders.slice(0,250).map(function(o){var oid=s_(o['Order ID']),its=itemsByOrder[oid]||[];return {orderId:oid,orderedAt:fmtDT_(v947OrderDate_(o)),status:s_(o.Status),paymentType:s_(o['Payment Type']),paymentStatus:s_(o['Payment Status']),subtotal:n_(o.Subtotal),discount:n_(o.Discount),totalAmount:n_(v947First_(o,['Total Amount','Order Total','Amount'])),outstandingBefore:n_(o['Outstanding Before']),outstandingAfter:n_(o['Outstanding After']),deliverySlot:s_(o['Delivery Slot']),address:s_(o.Address),area:s_(o.Area),pincode:s_(o.Pincode),priority:s_(o.Priority),source:s_(o.Source),createdAt:fmtDT_(o['Created At']),updatedAt:fmtDT_(o['Updated At']),deliveredQuantity:its.reduce(function(a,i){return a+i.deliveredQuantity;},0),items:its};});
  var valid=allOrders.filter(function(o){return !v947Cancelled_(o.Status);}),gmv=valid.reduce(function(a,o){return a+n_(v947First_(o,['Total Amount','Order Total','Amount']));},0),delivered=allOrders.filter(function(o){return v947Delivered_(o.Status);}).length,cancelled=allOrders.filter(function(o){return v947Cancelled_(o.Status);}).length,returned=allOrders.filter(function(o){return v947ReturnLike_(o.Status);}).length;
  var collectionRows=[];try{collectionRows=rows_(V8.SHEETS.COLLECTIONS).filter(function(r){return s_(r['Vendor ID'])===vendorId||digits_(r.Mobile)===digits_(vendor.Mobile);});}catch(e){}
  var tickets=[];try{tickets=rows_(V8.SHEETS.SUPPORT).filter(function(r){return s_(r['Party ID'])===vendorId||digits_(r['Party ID'])===digits_(vendor.Mobile)||s_(r['Vendor ID'])===vendorId;});}catch(e){}
  var products=rows_(V8.SHEETS.PRODUCTS),pricing=[];try{pricing=rows_(V8.SHEETS.VENDOR_PRICING).filter(function(r){return s_(r['Vendor ID'])===vendorId;});}catch(e){}
  var priceByProduct={};pricing.forEach(function(r){var pid=s_(r['Product ID']);if(pid&&(v947Upper_(r.Status)==='ACTIVE'||!s_(r.Status)))priceByProduct[pid]=r;});
  var lat=n_(vendor.Latitude),lng=n_(vendor.Longitude),first=v947Date_(v947OrderDate_(allOrders[allOrders.length-1]||{})),last=v947Date_(v947OrderDate_(allOrders[0]||{})),months=first&&last?Math.max(1,(last.getFullYear()-first.getFullYear())*12+last.getMonth()-first.getMonth()+1):1;
  return {success:true,version:V947_C360_VERSION,readOnly:true,generatedAt:fmtDT_(now_()),vendor:{vendorId:vendorId,businessName:s_(vendor['Business Name']),ownerName:s_(vendor['Owner Name']),mobile:digits_(vendor.Mobile),whatsapp:digits_(vendor.WhatsApp||vendor.Mobile),vendorType:s_(vendor['Vendor Type']),area:s_(vendor.Area),address:s_(vendor.Address),pincode:s_(vendor.Pincode),latitude:lat,longitude:lng,mapUrl:lat&&lng?'https://www.google.com/maps?q='+lat+','+lng:'',paymentType:s_(vendor['Payment Type']),creditDays:n_(vendor['Credit Days']),creditLimit:n_(vendor['Credit Limit']),outstanding:n_(vendor.Outstanding),moq:n_(vendor.MOQ),deliveryFrequency:s_(vendor['Delivery Frequency']),preferredTime:s_(vendor['Preferred Time']),status:s_(vendor.Status),onboardingId:s_(vendor['Onboarding ID']),createdAt:fmtDT_(vendor['Created At']),updatedAt:fmtDT_(vendor['Updated At'])},metrics:{lifetimeGmv:gmv,orderCount:allOrders.length,delivered:delivered,cancelled:cancelled,returns:returned,returnRate:delivered?returned*100/delivered:0,averageOrderValue:valid.length?gmv/valid.length:0,lastOrder:last?fmtDT_(last):'',frequency:allOrders.length?(allOrders.length/months).toFixed(1)+' orders/month':'No orders'},orders:orders,collections:collectionRows.sort(function(a,b){return (v947Date_(v947First_(b,['Collected At','Paid At','Created At','Date']))||0)-(v947Date_(v947First_(a,['Collected At','Paid At','Created At','Date']))||0);}).slice(0,100).map(function(r){return {date:fmtDT_(v947First_(r,['Collected At','Paid At','Created At','Date'])),reference:s_(v947First_(r,['Collection ID','Reference ID','Transaction ID','Order ID'])),method:s_(v947First_(r,['Method','Payment Method','Mode'])),status:s_(r.Status),amount:n_(v947First_(r,['Amount','Collected Amount','Paid Amount']))};}),tickets:tickets.sort(function(a,b){return (v947Date_(b['Created At'])||0)-(v947Date_(a['Created At'])||0);}).slice(0,100).map(function(r){return {ticketId:s_(r['Ticket ID']),createdAt:fmtDT_(r['Created At']),category:s_(r.Category),subject:s_(r.Subject),description:s_(r.Description),orderId:s_(r['Order ID']),priority:s_(r.Priority),status:s_(r.Status),resolution:s_(r.Resolution)};}),pricing:products.filter(function(p){return s_(p['Product ID'])&&v947Upper_(p['B2B Status'])!=='INACTIVE';}).map(function(p){var pid=s_(p['Product ID']),r=priceByProduct[pid]||{},def=n_(p['B2B Default Price']),agreed=n_(r['Agreed Price']);return {productId:pid,productName:s_(p['Product Name']),defaultPrice:def,agreedPrice:agreed,effectivePrice:agreed||def,moq:n_(r.MOQ)||n_(p['B2B MOQ'])||1,qtyStep:n_(r['Qty Step'])||n_(p['Qty Step'])||1,status:s_(r.Status)||(s_(p['B2B Status'])||'ACTIVE')};})};
}

function getCustomer360HealthV947(){return {ok:true,version:V947_C360_VERSION,readOnly:true,requiresAdminOrSelectedStaff:true};}
